// "artist": {
//     "ids": {
//       "ac-id": "ACJP-TRC-000-C0021-6"
//     },
//     "name": "RADIO FISH",
//     "name_en": "Radio Fish",
//     "name_kana": "レディオフィッシュ"
//   },

// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Artist.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file tsuyogoro/sugorokuon/Artist.proto.
 */
export const file_tsuyogoro_sugorokuon_Artist = /*@__PURE__*/
  fileDesc("CiF0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9BcnRpc3QucHJvdG8SFHRzdXlvZ29yby5zdWdvcm9rdW9uIkQKBkFydGlzdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg4KBm5hbWVFbhgDIAEoCRIQCghuYW1lS2FuYRgEIAEoCULPAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQgtBcnRpc3RQcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z");

/**
 * Describes the message tsuyogoro.sugorokuon.Artist.
 * Use `create(ArtistSchema)` to create a new message.
 */
export const ArtistSchema = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Artist, 0);

