// "artist": {
//     "ids": {
//       "ac-id": "ACJP-TRC-000-C0021-6"
//     },
//     "name": "RADIO FISH",
//     "name_en": "Radio Fish",
//     "name_kana": "レディオフィッシュ"
//   },

// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Artist.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Artist.proto.
 */
export declare const file_tsuyogoro_sugorokuon_Artist: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.Artist
 */
export declare type Artist = Message<"tsuyogoro.sugorokuon.Artist"> & {
  /**
   * Memo: idsから作る
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string nameEn = 3;
   */
  nameEn: string;

  /**
   * @generated from field: string nameKana = 4;
   */
  nameKana: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Artist.
 * Use `create(ArtistSchema)` to create a new message.
 */
export declare const ArtistSchema: GenMessage<Artist>;

