// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/GetRegionResponse.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_tsuyogoro_sugorokuon_Region } from "./Region_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/GetRegionResponse.proto.
 */
export const file_tsuyogoro_sugorokuon_GetRegionResponse = /*@__PURE__*/
  fileDesc("Cix0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9HZXRSZWdpb25SZXNwb25zZS5wcm90bxIUdHN1eW9nb3JvLnN1Z29yb2t1b24iQgoRR2V0UmVnaW9uUmVzcG9uc2USLQoHcmVnaW9ucxgBIAMoCzIcLnRzdXlvZ29yby5zdWdvcm9rdW9uLlJlZ2lvbkLaAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQhZHZXRSZWdpb25SZXNwb25zZVByb3RvUAFaNWdpdGh1Yi5jb20vYnVmYnVpbGQvYnVmLXRvdXIvZ2VuL3RzdXlvZ29yby9zdWdvcm9rdW9uogIDVFNYqgIUVHN1eW9nb3JvLlN1Z29yb2t1b27KAhRUc3V5b2dvcm9cU3Vnb3Jva3VvbuICIFRzdXlvZ29yb1xTdWdvcm9rdW9uXEdQQk1ldGFkYXRh6gIVVHN1eW9nb3JvOjpTdWdvcm9rdW9uYgZwcm90bzM", [file_tsuyogoro_sugorokuon_Region]);

/**
 * Describes the message tsuyogoro.sugorokuon.GetRegionResponse.
 * Use `create(GetRegionResponseSchema)` to create a new message.
 */
export const GetRegionResponseSchema = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_GetRegionResponse, 0);

