// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/GetRegionResponse.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Region } from "./Region_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/GetRegionResponse.proto.
 */
export declare const file_tsuyogoro_sugorokuon_GetRegionResponse: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.GetRegionResponse
 */
export declare type GetRegionResponse = Message<"tsuyogoro.sugorokuon.GetRegionResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Region regions = 1;
   */
  regions: Region[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetRegionResponse.
 * Use `create(GetRegionResponseSchema)` to create a new message.
 */
export declare const GetRegionResponseSchema: GenMessage<GetRegionResponse>;

