// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/GetStationsResponse.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Station } from "./Station_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/GetStationsResponse.proto.
 */
export declare const file_tsuyogoro_sugorokuon_GetStationsResponse: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.GetStationResponse
 */
export declare type GetStationResponse = Message<"tsuyogoro.sugorokuon.GetStationResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Station stations = 1;
   */
  stations: Station[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetStationResponse.
 * Use `create(GetStationResponseSchema)` to create a new message.
 */
export declare const GetStationResponseSchema: GenMessage<GetStationResponse>;

