// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/GetStationsResponse.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/GetStationsResponse.proto.
 */
export const file_tsuyogoro_sugorokuon_GetStationsResponse = /*@__PURE__*/
  fileDesc("Ci50c3V5b2dvcm8vc3Vnb3Jva3Vvbi9HZXRTdGF0aW9uc1Jlc3BvbnNlLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiJFChJHZXRTdGF0aW9uUmVzcG9uc2USLwoIc3RhdGlvbnMYASADKAsyHS50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5TdGF0aW9uQtwBChhjb20udHN1eW9nb3JvLnN1Z29yb2t1b25CGEdldFN0YXRpb25zUmVzcG9uc2VQcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_tsuyogoro_sugorokuon_Station]);

/**
 * Describes the message tsuyogoro.sugorokuon.GetStationResponse.
 * Use `create(GetStationResponseSchema)` to create a new message.
 */
export const GetStationResponseSchema = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_GetStationsResponse, 0);

