// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/GetTimetableResponse.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timetable } from "./Timetable_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/GetTimetableResponse.proto.
 */
export declare const file_tsuyogoro_sugorokuon_GetTimetableResponse: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.GetTimetableResponse
 */
export declare type GetTimetableResponse = Message<"tsuyogoro.sugorokuon.GetTimetableResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Timetable timetables = 1;
   */
  timetables: Timetable[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetTimetableResponse.
 * Use `create(GetTimetableResponseSchema)` to create a new message.
 */
export declare const GetTimetableResponseSchema: GenMessage<GetTimetableResponse>;

