// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Program.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { DateTime } from "../../google/type/datetime_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/Program.proto.
 */
export declare const file_tsuyogoro_sugorokuon_Program: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.Program
 */
export declare type Program = Message<"tsuyogoro.sugorokuon.Program"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: google.type.DateTime startTime = 4;
   */
  startTime?: DateTime;

  /**
   * @generated from field: google.type.DateTime endTime = 5;
   */
  endTime?: DateTime;

  /**
   * @generated from field: string personalities = 6;
   */
  personalities: string;

  /**
   * @generated from field: string image = 7;
   */
  image: string;

  /**
   * @generated from field: string desc = 8;
   */
  desc: string;

  /**
   * @generated from field: string info = 9;
   */
  info: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Program.
 * Use `create(ProgramSchema)` to create a new message.
 */
export declare const ProgramSchema: GenMessage<Program>;

