// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Program.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_type_datetime } from "../../google/type/datetime_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/Program.proto.
 */
export const file_tsuyogoro_sugorokuon_Program = /*@__PURE__*/
  fileDesc("CiJ0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9Qcm9ncmFtLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiLFAQoHUHJvZ3JhbRIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRILCgN1cmwYAyABKAkSKAoJc3RhcnRUaW1lGAQgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWUSJgoHZW5kVGltZRgFIAEoCzIVLmdvb2dsZS50eXBlLkRhdGVUaW1lEhUKDXBlcnNvbmFsaXRpZXMYBiABKAkSDQoFaW1hZ2UYByABKAkSDAoEZGVzYxgIIAEoCRIMCgRpbmZvGAkgASgJQtABChhjb20udHN1eW9nb3JvLnN1Z29yb2t1b25CDFByb2dyYW1Qcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_google_type_datetime]);

/**
 * Describes the message tsuyogoro.sugorokuon.Program.
 * Use `create(ProgramSchema)` to create a new message.
 */
export const ProgramSchema = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Program, 0);

