// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/Program.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { DateTime } from "../../google/type/datetime_pb";
import { file_google_type_datetime } from "../../google/type/datetime_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Program.proto.
 */
export const file_tsuyogoro_sugorokuon_Program: GenFile = /*@__PURE__*/
  fileDesc("CiJ0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9Qcm9ncmFtLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiLFAQoHUHJvZ3JhbRIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRILCgN1cmwYAyABKAkSKAoJc3RhcnRUaW1lGAQgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWUSJgoHZW5kVGltZRgFIAEoCzIVLmdvb2dsZS50eXBlLkRhdGVUaW1lEhUKDXBlcnNvbmFsaXRpZXMYBiABKAkSDQoFaW1hZ2UYByABKAkSDAoEZGVzYxgIIAEoCRIMCgRpbmZvGAkgASgJQtABChhjb20udHN1eW9nb3JvLnN1Z29yb2t1b25CDFByb2dyYW1Qcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_google_type_datetime]);

/**
 * @generated from message tsuyogoro.sugorokuon.Program
 */
export type Program = Message<"tsuyogoro.sugorokuon.Program"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: google.type.DateTime startTime = 4;
   */
  startTime?: DateTime;

  /**
   * @generated from field: google.type.DateTime endTime = 5;
   */
  endTime?: DateTime;

  /**
   * @generated from field: string personalities = 6;
   */
  personalities: string;

  /**
   * @generated from field: string image = 7;
   */
  image: string;

  /**
   * @generated from field: string desc = 8;
   */
  desc: string;

  /**
   * @generated from field: string info = 9;
   */
  info: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Program.
 * Use `create(ProgramSchema)` to create a new message.
 */
export const ProgramSchema: GenMessage<Program> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Program, 0);

