// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/Region.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Station } from "./Station_pb";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Region.proto.
 */
export const file_tsuyogoro_sugorokuon_Region: GenFile = /*@__PURE__*/
  fileDesc("CiF0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9SZWdpb24ucHJvdG8SFHRzdXlvZ29yby5zdWdvcm9rdW9uIlMKBlJlZ2lvbhIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEi8KCHN0YXRpb25zGAMgAygLMh0udHN1eW9nb3JvLnN1Z29yb2t1b24uU3RhdGlvbkLPAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQgtSZWdpb25Qcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_tsuyogoro_sugorokuon_Station]);

/**
 * @generated from message tsuyogoro.sugorokuon.Region
 */
export type Region = Message<"tsuyogoro.sugorokuon.Region"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Station stations = 3;
   */
  stations: Station[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.Region.
 * Use `create(RegionSchema)` to create a new message.
 */
export const RegionSchema: GenMessage<Region> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Region, 0);

