// "artist_name": "RADIO FISH",
// "displayed_start_time": "2024-12-30T16:10:23+09:00",
// "id": "2024-12-30T16:10:23-BAYFM78",
// "music": {
//   "image": {
//     "large": "https://m.media-amazon.com/images/I/51vJoXLBy0L._SL500_.jpg",
//     "medium": "https://m.media-amazon.com/images/I/51vJoXLBy0L._SL160_.jpg",
//     "small": "https://m.media-amazon.com/images/I/51vJoXLBy0L._SL75_.jpg"
//   },
//   "shops": {
//     "amazon": "https://www.amazon.co.jp/dp/B01CUDKZWM?tag=radiko-22&linkCode=osi&th=1&psc=1",
//     "itunes": "https://music.apple.com/jp/album/perfect-human/1068345391?i=1068345393&uo=4&at=1014xm&apo=itunes",
//     "recochoku": "https://recochoku.jp/song/S1002580717/?affiliate=6501010009"
//   }
// },
// "title": "PERFECT HUMAN"

// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Song.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Artist } from "./Artist_pb";
import type { DateTime } from "../../google/type/datetime_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/Song.proto.
 */
export declare const file_tsuyogoro_sugorokuon_Song: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.SongThumbnail
 */
export declare type SongThumbnail = Message<"tsuyogoro.sugorokuon.SongThumbnail"> & {
  /**
   * @generated from field: string small = 1;
   */
  small: string;

  /**
   * @generated from field: string medium = 2;
   */
  medium: string;

  /**
   * @generated from field: string large = 3;
   */
  large: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.SongThumbnail.
 * Use `create(SongThumbnailSchema)` to create a new message.
 */
export declare const SongThumbnailSchema: GenMessage<SongThumbnail>;

/**
 * @generated from message tsuyogoro.sugorokuon.Song
 */
export declare type Song = Message<"tsuyogoro.sugorokuon.Song"> & {
  /**
   * @generated from field: tsuyogoro.sugorokuon.Artist artist = 1;
   */
  artist?: Artist;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3;
   */
  thumbnails?: SongThumbnail;

  /**
   * @generated from field: google.type.DateTime onAirTime = 4;
   */
  onAirTime?: DateTime;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Song.
 * Use `create(SongSchema)` to create a new message.
 */
export declare const SongSchema: GenMessage<Song>;

