// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/SongService.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Song } from "./Song_pb";
import { file_tsuyogoro_sugorokuon_Song } from "./Song_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/SongService.proto.
 */
export const file_tsuyogoro_sugorokuon_SongService: GenFile = /*@__PURE__*/
  fileDesc("CiZ0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9Tb25nU2VydmljZS5wcm90bxIUdHN1eW9nb3JvLnN1Z29yb2t1b24iRgoZR2V0U29uZ3NCeVN0YXRpb25SZXNwb25zZRIpCgVzb25ncxgBIAMoCzIaLnRzdXlvZ29yby5zdWdvcm9rdW9uLlNvbmdC1AEKGGNvbS50c3V5b2dvcm8uc3Vnb3Jva3VvbkIQU29uZ1NlcnZpY2VQcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_tsuyogoro_sugorokuon_Song]);

/**
 * GET /songs/{stationId}
 *
 * @generated from message tsuyogoro.sugorokuon.GetSongsByStationResponse
 */
export type GetSongsByStationResponse = Message<"tsuyogoro.sugorokuon.GetSongsByStationResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Song songs = 1;
   */
  songs: Song[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetSongsByStationResponse.
 * Use `create(GetSongsByStationResponseSchema)` to create a new message.
 */
export const GetSongsByStationResponseSchema: GenMessage<GetSongsByStationResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_SongService, 0);

