// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/Station.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Station.proto.
 */
export const file_tsuyogoro_sugorokuon_Station: GenFile = /*@__PURE__*/
  fileDesc("CiJ0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9TdGF0aW9uLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiIjCgdTdGF0aW9uEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAlC0AEKGGNvbS50c3V5b2dvcm8uc3Vnb3Jva3VvbkIMU3RhdGlvblByb3RvUAFaNWdpdGh1Yi5jb20vYnVmYnVpbGQvYnVmLXRvdXIvZ2VuL3RzdXlvZ29yby9zdWdvcm9rdW9uogIDVFNYqgIUVHN1eW9nb3JvLlN1Z29yb2t1b27KAhRUc3V5b2dvcm9cU3Vnb3Jva3VvbuICIFRzdXlvZ29yb1xTdWdvcm9rdW9uXEdQQk1ldGFkYXRh6gIVVHN1eW9nb3JvOjpTdWdvcm9rdW9uYgZwcm90bzM");

/**
 * @generated from message tsuyogoro.sugorokuon.Station
 */
export type Station = Message<"tsuyogoro.sugorokuon.Station"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Station.
 * Use `create(StationSchema)` to create a new message.
 */
export const StationSchema: GenMessage<Station> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Station, 0);

