// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/StationService.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Station } from "./Station_pb";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";
import type { Region } from "./Region_pb";
import { file_tsuyogoro_sugorokuon_Region } from "./Region_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/StationService.proto.
 */
export const file_tsuyogoro_sugorokuon_StationService: GenFile = /*@__PURE__*/
  fileDesc("Cil0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9TdGF0aW9uU2VydmljZS5wcm90bxIUdHN1eW9nb3JvLnN1Z29yb2t1b24iRQoSR2V0U3RhdGlvblJlc3BvbnNlEi8KCHN0YXRpb25zGAEgAygLMh0udHN1eW9nb3JvLnN1Z29yb2t1b24uU3RhdGlvbiJ8ChtHZXRTdGF0aW9uc0J5UmVnaW9uUmVzcG9uc2USLAoGcmVnaW9uGAEgASgLMhwudHN1eW9nb3JvLnN1Z29yb2t1b24uUmVnaW9uEi8KCHN0YXRpb25zGAIgAygLMh0udHN1eW9nb3JvLnN1Z29yb2t1b24uU3RhdGlvbiJMChlHZXRTdGF0aW9uc0J5QXJlYVJlc3BvbnNlEi8KCHN0YXRpb25zGAEgAygLMh0udHN1eW9nb3JvLnN1Z29yb2t1b24uU3RhdGlvbkLXAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQhNTdGF0aW9uU2VydmljZVByb3RvUAFaNWdpdGh1Yi5jb20vYnVmYnVpbGQvYnVmLXRvdXIvZ2VuL3RzdXlvZ29yby9zdWdvcm9rdW9uogIDVFNYqgIUVHN1eW9nb3JvLlN1Z29yb2t1b27KAhRUc3V5b2dvcm9cU3Vnb3Jva3VvbuICIFRzdXlvZ29yb1xTdWdvcm9rdW9uXEdQQk1ldGFkYXRh6gIVVHN1eW9nb3JvOjpTdWdvcm9rdW9uYgZwcm90bzM", [file_tsuyogoro_sugorokuon_Station, file_tsuyogoro_sugorokuon_Region]);

/**
 * GET /stations
 *
 * @generated from message tsuyogoro.sugorokuon.GetStationResponse
 */
export type GetStationResponse = Message<"tsuyogoro.sugorokuon.GetStationResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Station stations = 1;
   */
  stations: Station[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetStationResponse.
 * Use `create(GetStationResponseSchema)` to create a new message.
 */
export const GetStationResponseSchema: GenMessage<GetStationResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_StationService, 0);

/**
 * GET /stations/region/{regionId}
 *
 * @generated from message tsuyogoro.sugorokuon.GetStationsByRegionResponse
 */
export type GetStationsByRegionResponse = Message<"tsuyogoro.sugorokuon.GetStationsByRegionResponse"> & {
  /**
   * @generated from field: tsuyogoro.sugorokuon.Region region = 1;
   */
  region?: Region;

  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Station stations = 2;
   */
  stations: Station[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetStationsByRegionResponse.
 * Use `create(GetStationsByRegionResponseSchema)` to create a new message.
 */
export const GetStationsByRegionResponseSchema: GenMessage<GetStationsByRegionResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_StationService, 1);

/**
 * GET /stations/area/{areaId}
 *
 * @generated from message tsuyogoro.sugorokuon.GetStationsByAreaResponse
 */
export type GetStationsByAreaResponse = Message<"tsuyogoro.sugorokuon.GetStationsByAreaResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Station stations = 1;
   */
  stations: Station[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetStationsByAreaResponse.
 * Use `create(GetStationsByAreaResponseSchema)` to create a new message.
 */
export const GetStationsByAreaResponseSchema: GenMessage<GetStationsByAreaResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_StationService, 2);

