// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/StationDetail.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";

/**
 * Describes the file tsuyogoro/sugorokuon/StationDetail.proto.
 */
export const file_tsuyogoro_sugorokuon_StationDetail = /*@__PURE__*/
  fileDesc("Cih0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9TdGF0aW9uRGV0YWlsLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiJMCg1TdGF0aW9uRGV0YWlsEi4KB3N0YXRpb24YASABKAsyHS50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5TdGF0aW9uEgsKA3VybBgCIAEoCULWAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQhJTdGF0aW9uRGV0YWlsUHJvdG9QAVo1Z2l0aHViLmNvbS9idWZidWlsZC9idWYtdG91ci9nZW4vdHN1eW9nb3JvL3N1Z29yb2t1b26iAgNUU1iqAhRUc3V5b2dvcm8uU3Vnb3Jva3VvbsoCFFRzdXlvZ29yb1xTdWdvcm9rdW9u4gIgVHN1eW9nb3JvXFN1Z29yb2t1b25cR1BCTWV0YWRhdGHqAhVUc3V5b2dvcm86OlN1Z29yb2t1b25iBnByb3RvMw", [file_tsuyogoro_sugorokuon_Station]);

/**
 * Describes the message tsuyogoro.sugorokuon.StationDetail.
 * Use `create(StationDetailSchema)` to create a new message.
 */
export const StationDetailSchema = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_StationDetail, 0);

