// @generated by protoc-gen-es v2.2.3
// @generated from file tsuyogoro/sugorokuon/Station.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Station.proto.
 */
export declare const file_tsuyogoro_sugorokuon_Station: GenFile;

/**
 * @generated from message tsuyogoro.sugorokuon.Station
 */
export declare type Station = Message<"tsuyogoro.sugorokuon.Station"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.Station.
 * Use `create(StationSchema)` to create a new message.
 */
export declare const StationSchema: GenMessage<Station>;

