// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/StationDetail.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Station } from "./Station_pb";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/StationDetail.proto.
 */
export const file_tsuyogoro_sugorokuon_StationDetail: GenFile = /*@__PURE__*/
  fileDesc("Cih0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9TdGF0aW9uRGV0YWlsLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiJMCg1TdGF0aW9uRGV0YWlsEi4KB3N0YXRpb24YASABKAsyHS50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5TdGF0aW9uEgsKA3VybBgCIAEoCULWAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQhJTdGF0aW9uRGV0YWlsUHJvdG9QAVo1Z2l0aHViLmNvbS9idWZidWlsZC9idWYtdG91ci9nZW4vdHN1eW9nb3JvL3N1Z29yb2t1b26iAgNUU1iqAhRUc3V5b2dvcm8uU3Vnb3Jva3VvbsoCFFRzdXlvZ29yb1xTdWdvcm9rdW9u4gIgVHN1eW9nb3JvXFN1Z29yb2t1b25cR1BCTWV0YWRhdGHqAhVUc3V5b2dvcm86OlN1Z29yb2t1b25iBnByb3RvMw", [file_tsuyogoro_sugorokuon_Station]);

/**
 * @generated from message tsuyogoro.sugorokuon.StationDetail
 */
export type StationDetail = Message<"tsuyogoro.sugorokuon.StationDetail"> & {
  /**
   * @generated from field: tsuyogoro.sugorokuon.Station station = 1;
   */
  station?: Station;

  /**
   * @generated from field: string url = 2;
   */
  url: string;
};

/**
 * Describes the message tsuyogoro.sugorokuon.StationDetail.
 * Use `create(StationDetailSchema)` to create a new message.
 */
export const StationDetailSchema: GenMessage<StationDetail> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_StationDetail, 0);

