// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/Timetable.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { DateTime } from "../../google/type/datetime_pb";
import { file_google_type_datetime } from "../../google/type/datetime_pb";
import type { Program } from "./Program_pb";
import { file_tsuyogoro_sugorokuon_Program } from "./Program_pb";
import type { Station } from "./Station_pb";
import { file_tsuyogoro_sugorokuon_Station } from "./Station_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/Timetable.proto.
 */
export const file_tsuyogoro_sugorokuon_Timetable: GenFile = /*@__PURE__*/
  fileDesc("CiR0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9UaW1ldGFibGUucHJvdG8SFHRzdXlvZ29yby5zdWdvcm9rdW9uIpEBCglUaW1ldGFibGUSIwoEZGF0ZRgBIAEoCzIVLmdvb2dsZS50eXBlLkRhdGVUaW1lEi4KB3N0YXRpb24YAiABKAsyHS50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5TdGF0aW9uEi8KCHByb2dyYW1zGAMgAygLMh0udHN1eW9nb3JvLnN1Z29yb2t1b24uUHJvZ3JhbULSAQoYY29tLnRzdXlvZ29yby5zdWdvcm9rdW9uQg5UaW1ldGFibGVQcm90b1ABWjVnaXRodWIuY29tL2J1ZmJ1aWxkL2J1Zi10b3VyL2dlbi90c3V5b2dvcm8vc3Vnb3Jva3VvbqICA1RTWKoCFFRzdXlvZ29yby5TdWdvcm9rdW9uygIUVHN1eW9nb3JvXFN1Z29yb2t1b27iAiBUc3V5b2dvcm9cU3Vnb3Jva3VvblxHUEJNZXRhZGF0YeoCFVRzdXlvZ29ybzo6U3Vnb3Jva3VvbmIGcHJvdG8z", [file_google_type_datetime, file_tsuyogoro_sugorokuon_Program, file_tsuyogoro_sugorokuon_Station]);

/**
 * @generated from message tsuyogoro.sugorokuon.Timetable
 */
export type Timetable = Message<"tsuyogoro.sugorokuon.Timetable"> & {
  /**
   * @generated from field: google.type.DateTime date = 1;
   */
  date?: DateTime;

  /**
   * @generated from field: tsuyogoro.sugorokuon.Station station = 2;
   */
  station?: Station;

  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Program programs = 3;
   */
  programs: Program[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.Timetable.
 * Use `create(TimetableSchema)` to create a new message.
 */
export const TimetableSchema: GenMessage<Timetable> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_Timetable, 0);

