// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file tsuyogoro/sugorokuon/TimetableService.proto (package tsuyogoro.sugorokuon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timetable } from "./Timetable_pb";
import { file_tsuyogoro_sugorokuon_Timetable } from "./Timetable_pb";
import type { Region } from "./Region_pb";
import { file_tsuyogoro_sugorokuon_Region } from "./Region_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tsuyogoro/sugorokuon/TimetableService.proto.
 */
export const file_tsuyogoro_sugorokuon_TimetableService: GenFile = /*@__PURE__*/
  fileDesc("Cit0c3V5b2dvcm8vc3Vnb3Jva3Vvbi9UaW1ldGFibGVTZXJ2aWNlLnByb3RvEhR0c3V5b2dvcm8uc3Vnb3Jva3VvbiJ+ChhHZXRBbGxUaW1ldGFibGVzUmVzcG9uc2USLQoHcmVnaW9ucxgBIAMoCzIcLnRzdXlvZ29yby5zdWdvcm9rdW9uLlJlZ2lvbhIzCgp0aW1ldGFibGVzGAIgAygLMh8udHN1eW9nb3JvLnN1Z29yb2t1b24uVGltZXRhYmxlIoIBCh1HZXRUaW1ldGFibGVzQnlSZWdpb25SZXNwb25zZRIsCgZyZWdpb24YASABKAsyHC50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5SZWdpb24SMwoKdGltZXRhYmxlcxgCIAMoCzIfLnRzdXlvZ29yby5zdWdvcm9rdW9uLlRpbWV0YWJsZSJSChtHZXRUaW1ldGFibGVzQnlBcmVhUmVzcG9uc2USMwoKdGltZXRhYmxlcxgBIAMoCzIfLnRzdXlvZ29yby5zdWdvcm9rdW9uLlRpbWV0YWJsZSJZCiJHZXRUaW1ldGFibGVzQnlBcmVhQW5kRGF0ZVJlc3BvbnNlEjMKCnRpbWV0YWJsZXMYASADKAsyHy50c3V5b2dvcm8uc3Vnb3Jva3Vvbi5UaW1ldGFibGVC2QEKGGNvbS50c3V5b2dvcm8uc3Vnb3Jva3VvbkIVVGltZXRhYmxlU2VydmljZVByb3RvUAFaNWdpdGh1Yi5jb20vYnVmYnVpbGQvYnVmLXRvdXIvZ2VuL3RzdXlvZ29yby9zdWdvcm9rdW9uogIDVFNYqgIUVHN1eW9nb3JvLlN1Z29yb2t1b27KAhRUc3V5b2dvcm9cU3Vnb3Jva3VvbuICIFRzdXlvZ29yb1xTdWdvcm9rdW9uXEdQQk1ldGFkYXRh6gIVVHN1eW9nb3JvOjpTdWdvcm9rdW9uYgZwcm90bzM", [file_tsuyogoro_sugorokuon_Timetable, file_tsuyogoro_sugorokuon_Region]);

/**
 * GET /timetables
 *
 * @generated from message tsuyogoro.sugorokuon.GetAllTimetablesResponse
 */
export type GetAllTimetablesResponse = Message<"tsuyogoro.sugorokuon.GetAllTimetablesResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Region regions = 1;
   */
  regions: Region[];

  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Timetable timetables = 2;
   */
  timetables: Timetable[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetAllTimetablesResponse.
 * Use `create(GetAllTimetablesResponseSchema)` to create a new message.
 */
export const GetAllTimetablesResponseSchema: GenMessage<GetAllTimetablesResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_TimetableService, 0);

/**
 * GET /timetables/region/{regionId} 
 *
 * @generated from message tsuyogoro.sugorokuon.GetTimetablesByRegionResponse
 */
export type GetTimetablesByRegionResponse = Message<"tsuyogoro.sugorokuon.GetTimetablesByRegionResponse"> & {
  /**
   * @generated from field: tsuyogoro.sugorokuon.Region region = 1;
   */
  region?: Region;

  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Timetable timetables = 2;
   */
  timetables: Timetable[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetTimetablesByRegionResponse.
 * Use `create(GetTimetablesByRegionResponseSchema)` to create a new message.
 */
export const GetTimetablesByRegionResponseSchema: GenMessage<GetTimetablesByRegionResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_TimetableService, 1);

/**
 * GET /timetables/area/{areaId}
 *
 * @generated from message tsuyogoro.sugorokuon.GetTimetablesByAreaResponse
 */
export type GetTimetablesByAreaResponse = Message<"tsuyogoro.sugorokuon.GetTimetablesByAreaResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Timetable timetables = 1;
   */
  timetables: Timetable[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetTimetablesByAreaResponse.
 * Use `create(GetTimetablesByAreaResponseSchema)` to create a new message.
 */
export const GetTimetablesByAreaResponseSchema: GenMessage<GetTimetablesByAreaResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_TimetableService, 2);

/**
 * GET /timetables/area/{areaId}/date/{date}
 *
 * @generated from message tsuyogoro.sugorokuon.GetTimetablesByAreaAndDateResponse
 */
export type GetTimetablesByAreaAndDateResponse = Message<"tsuyogoro.sugorokuon.GetTimetablesByAreaAndDateResponse"> & {
  /**
   * @generated from field: repeated tsuyogoro.sugorokuon.Timetable timetables = 1;
   */
  timetables: Timetable[];
};

/**
 * Describes the message tsuyogoro.sugorokuon.GetTimetablesByAreaAndDateResponse.
 * Use `create(GetTimetablesByAreaAndDateResponseSchema)` to create a new message.
 */
export const GetTimetablesByAreaAndDateResponseSchema: GenMessage<GetTimetablesByAreaAndDateResponse> = /*@__PURE__*/
  messageDesc(file_tsuyogoro_sugorokuon_TimetableService, 3);

