// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Artist.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class ArtistProto {
  private ArtistProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ArtistProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_Artist_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_Artist_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!tsuyogoro/sugorokuon/Artist.proto\022\024tsu" +
      "yogoro.sugorokuon\"`\n\006Artist\022\016\n\002id\030\001 \001(\tR" +
      "\002id\022\022\n\004name\030\002 \001(\tR\004name\022\026\n\006nameEn\030\003 \001(\tR" +
      "\006nameEn\022\032\n\010nameKana\030\004 \001(\tR\010nameKanaB\317\001\n\030" +
      "com.tsuyogoro.sugorokuonB\013ArtistProtoP\001Z" +
      "5github.com/bufbuild/buf-tour/gen/tsuyog" +
      "oro/sugorokuon\242\002\003TSX\252\002\024Tsuyogoro.Sugorok" +
      "uon\312\002\024Tsuyogoro\\Sugorokuon\342\002 Tsuyogoro\\S" +
      "ugorokuon\\GPBMetadata\352\002\025Tsuyogoro::Sugor" +
      "okuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tsuyogoro_sugorokuon_Artist_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_Artist_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_Artist_descriptor,
        new java.lang.String[] { "Id", "Name", "NameEn", "NameKana", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
