// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Artist.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface ArtistOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.Artist)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Memo: idsから作る
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Memo: idsから作る
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string nameEn = 3 [json_name = "nameEn"];</code>
   * @return The nameEn.
   */
  java.lang.String getNameEn();
  /**
   * <code>string nameEn = 3 [json_name = "nameEn"];</code>
   * @return The bytes for nameEn.
   */
  com.google.protobuf.ByteString
      getNameEnBytes();

  /**
   * <code>string nameKana = 4 [json_name = "nameKana"];</code>
   * @return The nameKana.
   */
  java.lang.String getNameKana();
  /**
   * <code>string nameKana = 4 [json_name = "nameKana"];</code>
   * @return The bytes for nameKana.
   */
  com.google.protobuf.ByteString
      getNameKanaBytes();
}
