// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/GetRegionResponse.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface GetRegionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.GetRegionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Region> 
      getRegionsList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  com.tsuyogoro.sugorokuon.Region getRegions(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  int getRegionsCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.RegionOrBuilder> 
      getRegionsOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionsOrBuilder(
      int index);
}
