// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/GetRegionResponse.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * Protobuf type {@code tsuyogoro.sugorokuon.GetRegionResponse}
 */
public final class GetRegionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.GetRegionResponse)
    GetRegionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetRegionResponse.class.getName());
  }
  // Use GetRegionResponse.newBuilder() to construct.
  private GetRegionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetRegionResponse() {
    regions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.GetRegionResponseProto.internal_static_tsuyogoro_sugorokuon_GetRegionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.GetRegionResponseProto.internal_static_tsuyogoro_sugorokuon_GetRegionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.GetRegionResponse.class, com.tsuyogoro.sugorokuon.GetRegionResponse.Builder.class);
  }

  public static final int REGIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Region> regions_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Region> getRegionsList() {
    return regions_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.RegionOrBuilder> 
      getRegionsOrBuilderList() {
    return regions_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  @java.lang.Override
  public int getRegionsCount() {
    return regions_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Region getRegions(int index) {
    return regions_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionsOrBuilder(
      int index) {
    return regions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < regions_.size(); i++) {
      output.writeMessage(1, regions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < regions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, regions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.GetRegionResponse)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.GetRegionResponse other = (com.tsuyogoro.sugorokuon.GetRegionResponse) obj;

    if (!getRegionsList()
        .equals(other.getRegionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRegionsCount() > 0) {
      hash = (37 * hash) + REGIONS_FIELD_NUMBER;
      hash = (53 * hash) + getRegionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetRegionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.GetRegionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tsuyogoro.sugorokuon.GetRegionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.GetRegionResponse)
      com.tsuyogoro.sugorokuon.GetRegionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.GetRegionResponseProto.internal_static_tsuyogoro_sugorokuon_GetRegionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.GetRegionResponseProto.internal_static_tsuyogoro_sugorokuon_GetRegionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.GetRegionResponse.class, com.tsuyogoro.sugorokuon.GetRegionResponse.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.GetRegionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (regionsBuilder_ == null) {
        regions_ = java.util.Collections.emptyList();
      } else {
        regions_ = null;
        regionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.GetRegionResponseProto.internal_static_tsuyogoro_sugorokuon_GetRegionResponse_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetRegionResponse getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.GetRegionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetRegionResponse build() {
      com.tsuyogoro.sugorokuon.GetRegionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetRegionResponse buildPartial() {
      com.tsuyogoro.sugorokuon.GetRegionResponse result = new com.tsuyogoro.sugorokuon.GetRegionResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.GetRegionResponse result) {
      if (regionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          regions_ = java.util.Collections.unmodifiableList(regions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.regions_ = regions_;
      } else {
        result.regions_ = regionsBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.GetRegionResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.GetRegionResponse) {
        return mergeFrom((com.tsuyogoro.sugorokuon.GetRegionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.GetRegionResponse other) {
      if (other == com.tsuyogoro.sugorokuon.GetRegionResponse.getDefaultInstance()) return this;
      if (regionsBuilder_ == null) {
        if (!other.regions_.isEmpty()) {
          if (regions_.isEmpty()) {
            regions_ = other.regions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRegionsIsMutable();
            regions_.addAll(other.regions_);
          }
          onChanged();
        }
      } else {
        if (!other.regions_.isEmpty()) {
          if (regionsBuilder_.isEmpty()) {
            regionsBuilder_.dispose();
            regionsBuilder_ = null;
            regions_ = other.regions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            regionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRegionsFieldBuilder() : null;
          } else {
            regionsBuilder_.addAllMessages(other.regions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.tsuyogoro.sugorokuon.Region m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Region.parser(),
                      extensionRegistry);
              if (regionsBuilder_ == null) {
                ensureRegionsIsMutable();
                regions_.add(m);
              } else {
                regionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tsuyogoro.sugorokuon.Region> regions_ =
      java.util.Collections.emptyList();
    private void ensureRegionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        regions_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Region>(regions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder> regionsBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Region> getRegionsList() {
      if (regionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(regions_);
      } else {
        return regionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public int getRegionsCount() {
      if (regionsBuilder_ == null) {
        return regions_.size();
      } else {
        return regionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public com.tsuyogoro.sugorokuon.Region getRegions(int index) {
      if (regionsBuilder_ == null) {
        return regions_.get(index);
      } else {
        return regionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder setRegions(
        int index, com.tsuyogoro.sugorokuon.Region value) {
      if (regionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionsIsMutable();
        regions_.set(index, value);
        onChanged();
      } else {
        regionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder setRegions(
        int index, com.tsuyogoro.sugorokuon.Region.Builder builderForValue) {
      if (regionsBuilder_ == null) {
        ensureRegionsIsMutable();
        regions_.set(index, builderForValue.build());
        onChanged();
      } else {
        regionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder addRegions(com.tsuyogoro.sugorokuon.Region value) {
      if (regionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionsIsMutable();
        regions_.add(value);
        onChanged();
      } else {
        regionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder addRegions(
        int index, com.tsuyogoro.sugorokuon.Region value) {
      if (regionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionsIsMutable();
        regions_.add(index, value);
        onChanged();
      } else {
        regionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder addRegions(
        com.tsuyogoro.sugorokuon.Region.Builder builderForValue) {
      if (regionsBuilder_ == null) {
        ensureRegionsIsMutable();
        regions_.add(builderForValue.build());
        onChanged();
      } else {
        regionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder addRegions(
        int index, com.tsuyogoro.sugorokuon.Region.Builder builderForValue) {
      if (regionsBuilder_ == null) {
        ensureRegionsIsMutable();
        regions_.add(index, builderForValue.build());
        onChanged();
      } else {
        regionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder addAllRegions(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Region> values) {
      if (regionsBuilder_ == null) {
        ensureRegionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, regions_);
        onChanged();
      } else {
        regionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder clearRegions() {
      if (regionsBuilder_ == null) {
        regions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        regionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public Builder removeRegions(int index) {
      if (regionsBuilder_ == null) {
        ensureRegionsIsMutable();
        regions_.remove(index);
        onChanged();
      } else {
        regionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public com.tsuyogoro.sugorokuon.Region.Builder getRegionsBuilder(
        int index) {
      return getRegionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionsOrBuilder(
        int index) {
      if (regionsBuilder_ == null) {
        return regions_.get(index);  } else {
        return regionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.RegionOrBuilder> 
         getRegionsOrBuilderList() {
      if (regionsBuilder_ != null) {
        return regionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(regions_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public com.tsuyogoro.sugorokuon.Region.Builder addRegionsBuilder() {
      return getRegionsFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Region.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public com.tsuyogoro.sugorokuon.Region.Builder addRegionsBuilder(
        int index) {
      return getRegionsFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Region.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Region.Builder> 
         getRegionsBuilderList() {
      return getRegionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder> 
        getRegionsFieldBuilder() {
      if (regionsBuilder_ == null) {
        regionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder>(
                regions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        regions_ = null;
      }
      return regionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.GetRegionResponse)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.GetRegionResponse)
  private static final com.tsuyogoro.sugorokuon.GetRegionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.GetRegionResponse();
  }

  public static com.tsuyogoro.sugorokuon.GetRegionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRegionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRegionResponse>() {
    @java.lang.Override
    public GetRegionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRegionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRegionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.GetRegionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

