// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/GetRegionResponse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.tsuyogoro.sugorokuon;

@kotlin.jvm.JvmName("-initializegetRegionResponse")
public inline fun getRegionResponse(block: com.tsuyogoro.sugorokuon.GetRegionResponseKt.Dsl.() -> kotlin.Unit): com.tsuyogoro.sugorokuon.GetRegionResponse =
  com.tsuyogoro.sugorokuon.GetRegionResponseKt.Dsl._create(com.tsuyogoro.sugorokuon.GetRegionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `tsuyogoro.sugorokuon.GetRegionResponse`
 */
public object GetRegionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.tsuyogoro.sugorokuon.GetRegionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.tsuyogoro.sugorokuon.GetRegionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.tsuyogoro.sugorokuon.GetRegionResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RegionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     */
     public val regions: com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.regionsList
      )
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     * @param value The regions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRegions")
    public fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.add(value: com.tsuyogoro.sugorokuon.Region) {
      _builder.addRegions(value)
    }
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     * @param value The regions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRegions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.plusAssign(value: com.tsuyogoro.sugorokuon.Region) {
      add(value)
    }
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     * @param values The regions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRegions")
    public fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.addAll(values: kotlin.collections.Iterable<com.tsuyogoro.sugorokuon.Region>) {
      _builder.addAllRegions(values)
    }
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     * @param values The regions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRegions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.plusAssign(values: kotlin.collections.Iterable<com.tsuyogoro.sugorokuon.Region>) {
      addAll(values)
    }
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     * @param index The index to set the value at.
     * @param value The regions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRegions")
    public operator fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.set(index: kotlin.Int, value: com.tsuyogoro.sugorokuon.Region) {
      _builder.setRegions(index, value)
    }
    /**
     * `repeated .tsuyogoro.sugorokuon.Region regions = 1 [json_name = "regions"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRegions")
    public fun com.google.protobuf.kotlin.DslList<com.tsuyogoro.sugorokuon.Region, RegionsProxy>.clear() {
      _builder.clearRegions()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.tsuyogoro.sugorokuon.GetRegionResponse.copy(block: `com.tsuyogoro.sugorokuon`.GetRegionResponseKt.Dsl.() -> kotlin.Unit): com.tsuyogoro.sugorokuon.GetRegionResponse =
  `com.tsuyogoro.sugorokuon`.GetRegionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

