// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/SongService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface GetSongsByStationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.GetSongsByStationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Song> 
      getSongsList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  com.tsuyogoro.sugorokuon.Song getSongs(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  int getSongsCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.SongOrBuilder> 
      getSongsOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  com.tsuyogoro.sugorokuon.SongOrBuilder getSongsOrBuilder(
      int index);
}
