// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * <pre>
 * GET /stations/region/{regionId}
 * </pre>
 *
 * Protobuf type {@code tsuyogoro.sugorokuon.GetStationsByRegionResponse}
 */
public final class GetStationsByRegionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.GetStationsByRegionResponse)
    GetStationsByRegionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetStationsByRegionResponse.class.getName());
  }
  // Use GetStationsByRegionResponse.newBuilder() to construct.
  private GetStationsByRegionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetStationsByRegionResponse() {
    stations_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.StationServiceProto.internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.StationServiceProto.internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.class, com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REGION_FIELD_NUMBER = 1;
  private com.tsuyogoro.sugorokuon.Region region_;
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return Whether the region field is set.
   */
  @java.lang.Override
  public boolean hasRegion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return The region.
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Region getRegion() {
    return region_ == null ? com.tsuyogoro.sugorokuon.Region.getDefaultInstance() : region_;
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionOrBuilder() {
    return region_ == null ? com.tsuyogoro.sugorokuon.Region.getDefaultInstance() : region_;
  }

  public static final int STATIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Station> stations_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Station> getStationsList() {
    return stations_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
      getStationsOrBuilderList() {
    return stations_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public int getStationsCount() {
    return stations_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Station getStations(int index) {
    return stations_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
      int index) {
    return stations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRegion());
    }
    for (int i = 0; i < stations_.size(); i++) {
      output.writeMessage(2, stations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRegion());
    }
    for (int i = 0; i < stations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, stations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.GetStationsByRegionResponse)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.GetStationsByRegionResponse other = (com.tsuyogoro.sugorokuon.GetStationsByRegionResponse) obj;

    if (hasRegion() != other.hasRegion()) return false;
    if (hasRegion()) {
      if (!getRegion()
          .equals(other.getRegion())) return false;
    }
    if (!getStationsList()
        .equals(other.getStationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRegion()) {
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
    }
    if (getStationsCount() > 0) {
      hash = (37 * hash) + STATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getStationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.GetStationsByRegionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GET /stations/region/{regionId}
   * </pre>
   *
   * Protobuf type {@code tsuyogoro.sugorokuon.GetStationsByRegionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.GetStationsByRegionResponse)
      com.tsuyogoro.sugorokuon.GetStationsByRegionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.StationServiceProto.internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.StationServiceProto.internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.class, com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRegionFieldBuilder();
        getStationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      region_ = null;
      if (regionBuilder_ != null) {
        regionBuilder_.dispose();
        regionBuilder_ = null;
      }
      if (stationsBuilder_ == null) {
        stations_ = java.util.Collections.emptyList();
      } else {
        stations_ = null;
        stationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.StationServiceProto.internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetStationsByRegionResponse getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetStationsByRegionResponse build() {
      com.tsuyogoro.sugorokuon.GetStationsByRegionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetStationsByRegionResponse buildPartial() {
      com.tsuyogoro.sugorokuon.GetStationsByRegionResponse result = new com.tsuyogoro.sugorokuon.GetStationsByRegionResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.GetStationsByRegionResponse result) {
      if (stationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          stations_ = java.util.Collections.unmodifiableList(stations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.stations_ = stations_;
      } else {
        result.stations_ = stationsBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.GetStationsByRegionResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.region_ = regionBuilder_ == null
            ? region_
            : regionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.GetStationsByRegionResponse) {
        return mergeFrom((com.tsuyogoro.sugorokuon.GetStationsByRegionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.GetStationsByRegionResponse other) {
      if (other == com.tsuyogoro.sugorokuon.GetStationsByRegionResponse.getDefaultInstance()) return this;
      if (other.hasRegion()) {
        mergeRegion(other.getRegion());
      }
      if (stationsBuilder_ == null) {
        if (!other.stations_.isEmpty()) {
          if (stations_.isEmpty()) {
            stations_ = other.stations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStationsIsMutable();
            stations_.addAll(other.stations_);
          }
          onChanged();
        }
      } else {
        if (!other.stations_.isEmpty()) {
          if (stationsBuilder_.isEmpty()) {
            stationsBuilder_.dispose();
            stationsBuilder_ = null;
            stations_ = other.stations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            stationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getStationsFieldBuilder() : null;
          } else {
            stationsBuilder_.addAllMessages(other.stations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRegionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.tsuyogoro.sugorokuon.Station m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Station.parser(),
                      extensionRegistry);
              if (stationsBuilder_ == null) {
                ensureStationsIsMutable();
                stations_.add(m);
              } else {
                stationsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.tsuyogoro.sugorokuon.Region region_;
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder> regionBuilder_;
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     * @return Whether the region field is set.
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     * @return The region.
     */
    public com.tsuyogoro.sugorokuon.Region getRegion() {
      if (regionBuilder_ == null) {
        return region_ == null ? com.tsuyogoro.sugorokuon.Region.getDefaultInstance() : region_;
      } else {
        return regionBuilder_.getMessage();
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public Builder setRegion(com.tsuyogoro.sugorokuon.Region value) {
      if (regionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        region_ = value;
      } else {
        regionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public Builder setRegion(
        com.tsuyogoro.sugorokuon.Region.Builder builderForValue) {
      if (regionBuilder_ == null) {
        region_ = builderForValue.build();
      } else {
        regionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public Builder mergeRegion(com.tsuyogoro.sugorokuon.Region value) {
      if (regionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          region_ != null &&
          region_ != com.tsuyogoro.sugorokuon.Region.getDefaultInstance()) {
          getRegionBuilder().mergeFrom(value);
        } else {
          region_ = value;
        }
      } else {
        regionBuilder_.mergeFrom(value);
      }
      if (region_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public Builder clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      region_ = null;
      if (regionBuilder_ != null) {
        regionBuilder_.dispose();
        regionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public com.tsuyogoro.sugorokuon.Region.Builder getRegionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRegionFieldBuilder().getBuilder();
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    public com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionOrBuilder() {
      if (regionBuilder_ != null) {
        return regionBuilder_.getMessageOrBuilder();
      } else {
        return region_ == null ?
            com.tsuyogoro.sugorokuon.Region.getDefaultInstance() : region_;
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder> 
        getRegionFieldBuilder() {
      if (regionBuilder_ == null) {
        regionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tsuyogoro.sugorokuon.Region, com.tsuyogoro.sugorokuon.Region.Builder, com.tsuyogoro.sugorokuon.RegionOrBuilder>(
                getRegion(),
                getParentForChildren(),
                isClean());
        region_ = null;
      }
      return regionBuilder_;
    }

    private java.util.List<com.tsuyogoro.sugorokuon.Station> stations_ =
      java.util.Collections.emptyList();
    private void ensureStationsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        stations_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Station>(stations_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> stationsBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Station> getStationsList() {
      if (stationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stations_);
      } else {
        return stationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public int getStationsCount() {
      if (stationsBuilder_ == null) {
        return stations_.size();
      } else {
        return stationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station getStations(int index) {
      if (stationsBuilder_ == null) {
        return stations_.get(index);
      } else {
        return stationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder setStations(
        int index, com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.set(index, value);
        onChanged();
      } else {
        stationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder setStations(
        int index, com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.set(index, builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder addStations(com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.add(value);
        onChanged();
      } else {
        stationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder addStations(
        int index, com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.add(index, value);
        onChanged();
      } else {
        stationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder addStations(
        com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.add(builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder addStations(
        int index, com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.add(index, builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder addAllStations(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Station> values) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stations_);
        onChanged();
      } else {
        stationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder clearStations() {
      if (stationsBuilder_ == null) {
        stations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        stationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public Builder removeStations(int index) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.remove(index);
        onChanged();
      } else {
        stationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder getStationsBuilder(
        int index) {
      return getStationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
        int index) {
      if (stationsBuilder_ == null) {
        return stations_.get(index);  } else {
        return stationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
         getStationsOrBuilderList() {
      if (stationsBuilder_ != null) {
        return stationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stations_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder addStationsBuilder() {
      return getStationsFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Station.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder addStationsBuilder(
        int index) {
      return getStationsFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Station.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Station.Builder> 
         getStationsBuilderList() {
      return getStationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> 
        getStationsFieldBuilder() {
      if (stationsBuilder_ == null) {
        stationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder>(
                stations_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        stations_ = null;
      }
      return stationsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.GetStationsByRegionResponse)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.GetStationsByRegionResponse)
  private static final com.tsuyogoro.sugorokuon.GetStationsByRegionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.GetStationsByRegionResponse();
  }

  public static com.tsuyogoro.sugorokuon.GetStationsByRegionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStationsByRegionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetStationsByRegionResponse>() {
    @java.lang.Override
    public GetStationsByRegionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetStationsByRegionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStationsByRegionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.GetStationsByRegionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

