// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/SongService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * <pre>
 * GET /songs/{stationId}
 * </pre>
 *
 * Protobuf type {@code tsuyogoro.sugorokuon.GetSongsByStationResponse}
 */
public final class GetSongsByStationResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.GetSongsByStationResponse)
    GetSongsByStationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetSongsByStationResponse.class.getName());
  }
  // Use GetSongsByStationResponse.newBuilder() to construct.
  private GetSongsByStationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSongsByStationResponse() {
    songs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.SongServiceProto.internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.SongServiceProto.internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.GetSongsByStationResponse.class, com.tsuyogoro.sugorokuon.GetSongsByStationResponse.Builder.class);
  }

  public static final int SONGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Song> songs_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Song> getSongsList() {
    return songs_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.SongOrBuilder> 
      getSongsOrBuilderList() {
    return songs_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  @java.lang.Override
  public int getSongsCount() {
    return songs_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Song getSongs(int index) {
    return songs_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.SongOrBuilder getSongsOrBuilder(
      int index) {
    return songs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < songs_.size(); i++) {
      output.writeMessage(1, songs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < songs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, songs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.GetSongsByStationResponse)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.GetSongsByStationResponse other = (com.tsuyogoro.sugorokuon.GetSongsByStationResponse) obj;

    if (!getSongsList()
        .equals(other.getSongsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSongsCount() > 0) {
      hash = (37 * hash) + SONGS_FIELD_NUMBER;
      hash = (53 * hash) + getSongsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.GetSongsByStationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GET /songs/{stationId}
   * </pre>
   *
   * Protobuf type {@code tsuyogoro.sugorokuon.GetSongsByStationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.GetSongsByStationResponse)
      com.tsuyogoro.sugorokuon.GetSongsByStationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.SongServiceProto.internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.SongServiceProto.internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.GetSongsByStationResponse.class, com.tsuyogoro.sugorokuon.GetSongsByStationResponse.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.GetSongsByStationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (songsBuilder_ == null) {
        songs_ = java.util.Collections.emptyList();
      } else {
        songs_ = null;
        songsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.SongServiceProto.internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetSongsByStationResponse getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.GetSongsByStationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetSongsByStationResponse build() {
      com.tsuyogoro.sugorokuon.GetSongsByStationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetSongsByStationResponse buildPartial() {
      com.tsuyogoro.sugorokuon.GetSongsByStationResponse result = new com.tsuyogoro.sugorokuon.GetSongsByStationResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.GetSongsByStationResponse result) {
      if (songsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          songs_ = java.util.Collections.unmodifiableList(songs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.songs_ = songs_;
      } else {
        result.songs_ = songsBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.GetSongsByStationResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.GetSongsByStationResponse) {
        return mergeFrom((com.tsuyogoro.sugorokuon.GetSongsByStationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.GetSongsByStationResponse other) {
      if (other == com.tsuyogoro.sugorokuon.GetSongsByStationResponse.getDefaultInstance()) return this;
      if (songsBuilder_ == null) {
        if (!other.songs_.isEmpty()) {
          if (songs_.isEmpty()) {
            songs_ = other.songs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSongsIsMutable();
            songs_.addAll(other.songs_);
          }
          onChanged();
        }
      } else {
        if (!other.songs_.isEmpty()) {
          if (songsBuilder_.isEmpty()) {
            songsBuilder_.dispose();
            songsBuilder_ = null;
            songs_ = other.songs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            songsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSongsFieldBuilder() : null;
          } else {
            songsBuilder_.addAllMessages(other.songs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.tsuyogoro.sugorokuon.Song m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Song.parser(),
                      extensionRegistry);
              if (songsBuilder_ == null) {
                ensureSongsIsMutable();
                songs_.add(m);
              } else {
                songsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tsuyogoro.sugorokuon.Song> songs_ =
      java.util.Collections.emptyList();
    private void ensureSongsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        songs_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Song>(songs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Song, com.tsuyogoro.sugorokuon.Song.Builder, com.tsuyogoro.sugorokuon.SongOrBuilder> songsBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Song> getSongsList() {
      if (songsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(songs_);
      } else {
        return songsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public int getSongsCount() {
      if (songsBuilder_ == null) {
        return songs_.size();
      } else {
        return songsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Song getSongs(int index) {
      if (songsBuilder_ == null) {
        return songs_.get(index);
      } else {
        return songsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder setSongs(
        int index, com.tsuyogoro.sugorokuon.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.set(index, value);
        onChanged();
      } else {
        songsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder setSongs(
        int index, com.tsuyogoro.sugorokuon.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.set(index, builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder addSongs(com.tsuyogoro.sugorokuon.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.add(value);
        onChanged();
      } else {
        songsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder addSongs(
        int index, com.tsuyogoro.sugorokuon.Song value) {
      if (songsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSongsIsMutable();
        songs_.add(index, value);
        onChanged();
      } else {
        songsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder addSongs(
        com.tsuyogoro.sugorokuon.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.add(builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder addSongs(
        int index, com.tsuyogoro.sugorokuon.Song.Builder builderForValue) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.add(index, builderForValue.build());
        onChanged();
      } else {
        songsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder addAllSongs(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Song> values) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, songs_);
        onChanged();
      } else {
        songsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder clearSongs() {
      if (songsBuilder_ == null) {
        songs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        songsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public Builder removeSongs(int index) {
      if (songsBuilder_ == null) {
        ensureSongsIsMutable();
        songs_.remove(index);
        onChanged();
      } else {
        songsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Song.Builder getSongsBuilder(
        int index) {
      return getSongsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public com.tsuyogoro.sugorokuon.SongOrBuilder getSongsOrBuilder(
        int index) {
      if (songsBuilder_ == null) {
        return songs_.get(index);  } else {
        return songsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.SongOrBuilder> 
         getSongsOrBuilderList() {
      if (songsBuilder_ != null) {
        return songsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(songs_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Song.Builder addSongsBuilder() {
      return getSongsFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Song.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Song.Builder addSongsBuilder(
        int index) {
      return getSongsFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Song.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Song songs = 1 [json_name = "songs"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Song.Builder> 
         getSongsBuilderList() {
      return getSongsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Song, com.tsuyogoro.sugorokuon.Song.Builder, com.tsuyogoro.sugorokuon.SongOrBuilder> 
        getSongsFieldBuilder() {
      if (songsBuilder_ == null) {
        songsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Song, com.tsuyogoro.sugorokuon.Song.Builder, com.tsuyogoro.sugorokuon.SongOrBuilder>(
                songs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        songs_ = null;
      }
      return songsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.GetSongsByStationResponse)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.GetSongsByStationResponse)
  private static final com.tsuyogoro.sugorokuon.GetSongsByStationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.GetSongsByStationResponse();
  }

  public static com.tsuyogoro.sugorokuon.GetSongsByStationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSongsByStationResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSongsByStationResponse>() {
    @java.lang.Override
    public GetSongsByStationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSongsByStationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSongsByStationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.GetSongsByStationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

