// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface GetStationsByAreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.GetStationsByAreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 1 [json_name = "stations"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Station> 
      getStationsList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 1 [json_name = "stations"];</code>
   */
  com.tsuyogoro.sugorokuon.Station getStations(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 1 [json_name = "stations"];</code>
   */
  int getStationsCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 1 [json_name = "stations"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
      getStationsOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 1 [json_name = "stations"];</code>
   */
  com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
      int index);
}
