// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface GetStationsByRegionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.GetStationsByRegionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return The region.
   */
  com.tsuyogoro.sugorokuon.Region getRegion();
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   */
  com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionOrBuilder();

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Station> 
      getStationsList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  com.tsuyogoro.sugorokuon.Station getStations(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  int getStationsCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
      getStationsOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 2 [json_name = "stations"];</code>
   */
  com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
      int index);
}
