// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/GetTimetableResponse.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * Protobuf type {@code tsuyogoro.sugorokuon.GetTimetableResponse}
 */
public final class GetTimetableResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.GetTimetableResponse)
    GetTimetableResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetTimetableResponse.class.getName());
  }
  // Use GetTimetableResponse.newBuilder() to construct.
  private GetTimetableResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetTimetableResponse() {
    timetables_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.GetTimetableResponseProto.internal_static_tsuyogoro_sugorokuon_GetTimetableResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.GetTimetableResponseProto.internal_static_tsuyogoro_sugorokuon_GetTimetableResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.GetTimetableResponse.class, com.tsuyogoro.sugorokuon.GetTimetableResponse.Builder.class);
  }

  public static final int TIMETABLES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Timetable> timetables_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Timetable> getTimetablesList() {
    return timetables_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.TimetableOrBuilder> 
      getTimetablesOrBuilderList() {
    return timetables_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
   */
  @java.lang.Override
  public int getTimetablesCount() {
    return timetables_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Timetable getTimetables(int index) {
    return timetables_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.TimetableOrBuilder getTimetablesOrBuilder(
      int index) {
    return timetables_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < timetables_.size(); i++) {
      output.writeMessage(1, timetables_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < timetables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, timetables_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.GetTimetableResponse)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.GetTimetableResponse other = (com.tsuyogoro.sugorokuon.GetTimetableResponse) obj;

    if (!getTimetablesList()
        .equals(other.getTimetablesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTimetablesCount() > 0) {
      hash = (37 * hash) + TIMETABLES_FIELD_NUMBER;
      hash = (53 * hash) + getTimetablesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.GetTimetableResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.GetTimetableResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tsuyogoro.sugorokuon.GetTimetableResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.GetTimetableResponse)
      com.tsuyogoro.sugorokuon.GetTimetableResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.GetTimetableResponseProto.internal_static_tsuyogoro_sugorokuon_GetTimetableResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.GetTimetableResponseProto.internal_static_tsuyogoro_sugorokuon_GetTimetableResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.GetTimetableResponse.class, com.tsuyogoro.sugorokuon.GetTimetableResponse.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.GetTimetableResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (timetablesBuilder_ == null) {
        timetables_ = java.util.Collections.emptyList();
      } else {
        timetables_ = null;
        timetablesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.GetTimetableResponseProto.internal_static_tsuyogoro_sugorokuon_GetTimetableResponse_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetTimetableResponse getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.GetTimetableResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetTimetableResponse build() {
      com.tsuyogoro.sugorokuon.GetTimetableResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.GetTimetableResponse buildPartial() {
      com.tsuyogoro.sugorokuon.GetTimetableResponse result = new com.tsuyogoro.sugorokuon.GetTimetableResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.GetTimetableResponse result) {
      if (timetablesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          timetables_ = java.util.Collections.unmodifiableList(timetables_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.timetables_ = timetables_;
      } else {
        result.timetables_ = timetablesBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.GetTimetableResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.GetTimetableResponse) {
        return mergeFrom((com.tsuyogoro.sugorokuon.GetTimetableResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.GetTimetableResponse other) {
      if (other == com.tsuyogoro.sugorokuon.GetTimetableResponse.getDefaultInstance()) return this;
      if (timetablesBuilder_ == null) {
        if (!other.timetables_.isEmpty()) {
          if (timetables_.isEmpty()) {
            timetables_ = other.timetables_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTimetablesIsMutable();
            timetables_.addAll(other.timetables_);
          }
          onChanged();
        }
      } else {
        if (!other.timetables_.isEmpty()) {
          if (timetablesBuilder_.isEmpty()) {
            timetablesBuilder_.dispose();
            timetablesBuilder_ = null;
            timetables_ = other.timetables_;
            bitField0_ = (bitField0_ & ~0x00000001);
            timetablesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTimetablesFieldBuilder() : null;
          } else {
            timetablesBuilder_.addAllMessages(other.timetables_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.tsuyogoro.sugorokuon.Timetable m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Timetable.parser(),
                      extensionRegistry);
              if (timetablesBuilder_ == null) {
                ensureTimetablesIsMutable();
                timetables_.add(m);
              } else {
                timetablesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tsuyogoro.sugorokuon.Timetable> timetables_ =
      java.util.Collections.emptyList();
    private void ensureTimetablesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        timetables_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Timetable>(timetables_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Timetable, com.tsuyogoro.sugorokuon.Timetable.Builder, com.tsuyogoro.sugorokuon.TimetableOrBuilder> timetablesBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Timetable> getTimetablesList() {
      if (timetablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timetables_);
      } else {
        return timetablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public int getTimetablesCount() {
      if (timetablesBuilder_ == null) {
        return timetables_.size();
      } else {
        return timetablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public com.tsuyogoro.sugorokuon.Timetable getTimetables(int index) {
      if (timetablesBuilder_ == null) {
        return timetables_.get(index);
      } else {
        return timetablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder setTimetables(
        int index, com.tsuyogoro.sugorokuon.Timetable value) {
      if (timetablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimetablesIsMutable();
        timetables_.set(index, value);
        onChanged();
      } else {
        timetablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder setTimetables(
        int index, com.tsuyogoro.sugorokuon.Timetable.Builder builderForValue) {
      if (timetablesBuilder_ == null) {
        ensureTimetablesIsMutable();
        timetables_.set(index, builderForValue.build());
        onChanged();
      } else {
        timetablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder addTimetables(com.tsuyogoro.sugorokuon.Timetable value) {
      if (timetablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimetablesIsMutable();
        timetables_.add(value);
        onChanged();
      } else {
        timetablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder addTimetables(
        int index, com.tsuyogoro.sugorokuon.Timetable value) {
      if (timetablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimetablesIsMutable();
        timetables_.add(index, value);
        onChanged();
      } else {
        timetablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder addTimetables(
        com.tsuyogoro.sugorokuon.Timetable.Builder builderForValue) {
      if (timetablesBuilder_ == null) {
        ensureTimetablesIsMutable();
        timetables_.add(builderForValue.build());
        onChanged();
      } else {
        timetablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder addTimetables(
        int index, com.tsuyogoro.sugorokuon.Timetable.Builder builderForValue) {
      if (timetablesBuilder_ == null) {
        ensureTimetablesIsMutable();
        timetables_.add(index, builderForValue.build());
        onChanged();
      } else {
        timetablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder addAllTimetables(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Timetable> values) {
      if (timetablesBuilder_ == null) {
        ensureTimetablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timetables_);
        onChanged();
      } else {
        timetablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder clearTimetables() {
      if (timetablesBuilder_ == null) {
        timetables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        timetablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public Builder removeTimetables(int index) {
      if (timetablesBuilder_ == null) {
        ensureTimetablesIsMutable();
        timetables_.remove(index);
        onChanged();
      } else {
        timetablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public com.tsuyogoro.sugorokuon.Timetable.Builder getTimetablesBuilder(
        int index) {
      return getTimetablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public com.tsuyogoro.sugorokuon.TimetableOrBuilder getTimetablesOrBuilder(
        int index) {
      if (timetablesBuilder_ == null) {
        return timetables_.get(index);  } else {
        return timetablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.TimetableOrBuilder> 
         getTimetablesOrBuilderList() {
      if (timetablesBuilder_ != null) {
        return timetablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timetables_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public com.tsuyogoro.sugorokuon.Timetable.Builder addTimetablesBuilder() {
      return getTimetablesFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Timetable.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public com.tsuyogoro.sugorokuon.Timetable.Builder addTimetablesBuilder(
        int index) {
      return getTimetablesFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Timetable.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 1 [json_name = "timetables"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Timetable.Builder> 
         getTimetablesBuilderList() {
      return getTimetablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Timetable, com.tsuyogoro.sugorokuon.Timetable.Builder, com.tsuyogoro.sugorokuon.TimetableOrBuilder> 
        getTimetablesFieldBuilder() {
      if (timetablesBuilder_ == null) {
        timetablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Timetable, com.tsuyogoro.sugorokuon.Timetable.Builder, com.tsuyogoro.sugorokuon.TimetableOrBuilder>(
                timetables_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        timetables_ = null;
      }
      return timetablesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.GetTimetableResponse)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.GetTimetableResponse)
  private static final com.tsuyogoro.sugorokuon.GetTimetableResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.GetTimetableResponse();
  }

  public static com.tsuyogoro.sugorokuon.GetTimetableResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTimetableResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTimetableResponse>() {
    @java.lang.Override
    public GetTimetableResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTimetableResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTimetableResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.GetTimetableResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

