// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/TimetableService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface GetTimetablesByRegionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.GetTimetablesByRegionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   * @return The region.
   */
  com.tsuyogoro.sugorokuon.Region getRegion();
  /**
   * <code>.tsuyogoro.sugorokuon.Region region = 1 [json_name = "region"];</code>
   */
  com.tsuyogoro.sugorokuon.RegionOrBuilder getRegionOrBuilder();

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 2 [json_name = "timetables"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Timetable> 
      getTimetablesList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 2 [json_name = "timetables"];</code>
   */
  com.tsuyogoro.sugorokuon.Timetable getTimetables(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 2 [json_name = "timetables"];</code>
   */
  int getTimetablesCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 2 [json_name = "timetables"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.TimetableOrBuilder> 
      getTimetablesOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Timetable timetables = 2 [json_name = "timetables"];</code>
   */
  com.tsuyogoro.sugorokuon.TimetableOrBuilder getTimetablesOrBuilder(
      int index);
}
