// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Program.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class ProgramProto {
  private ProgramProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ProgramProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_Program_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_Program_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"tsuyogoro/sugorokuon/Program.proto\022\024ts" +
      "uyogoro.sugorokuon\032\032google/type/datetime" +
      ".proto\"\213\002\n\007Program\022\016\n\002id\030\001 \001(\tR\002id\022\024\n\005ti" +
      "tle\030\002 \001(\tR\005title\022\020\n\003url\030\003 \001(\tR\003url\0223\n\tst" +
      "artTime\030\004 \001(\0132\025.google.type.DateTimeR\tst" +
      "artTime\022/\n\007endTime\030\005 \001(\0132\025.google.type.D" +
      "ateTimeR\007endTime\022$\n\rpersonalities\030\006 \001(\tR" +
      "\rpersonalities\022\024\n\005image\030\007 \001(\tR\005image\022\022\n\004" +
      "desc\030\010 \001(\tR\004desc\022\022\n\004info\030\t \001(\tR\004infoB\320\001\n" +
      "\030com.tsuyogoro.sugorokuonB\014ProgramProtoP" +
      "\001Z5github.com/bufbuild/buf-tour/gen/tsuy" +
      "ogoro/sugorokuon\242\002\003TSX\252\002\024Tsuyogoro.Sugor" +
      "okuon\312\002\024Tsuyogoro\\Sugorokuon\342\002 Tsuyogoro" +
      "\\Sugorokuon\\GPBMetadata\352\002\025Tsuyogoro::Sug" +
      "orokuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.DatetimeProto.getDescriptor(),
        });
    internal_static_tsuyogoro_sugorokuon_Program_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_Program_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_Program_descriptor,
        new java.lang.String[] { "Id", "Title", "Url", "StartTime", "EndTime", "Personalities", "Image", "Desc", "Info", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.type.DatetimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
