// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Region.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * Protobuf type {@code tsuyogoro.sugorokuon.Region}
 */
public final class Region extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.Region)
    RegionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Region.class.getName());
  }
  // Use Region.newBuilder() to construct.
  private Region(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Region() {
    id_ = "";
    name_ = "";
    stations_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.RegionProto.internal_static_tsuyogoro_sugorokuon_Region_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.RegionProto.internal_static_tsuyogoro_sugorokuon_Region_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.Region.class, com.tsuyogoro.sugorokuon.Region.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Station> stations_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Station> getStationsList() {
    return stations_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
      getStationsOrBuilderList() {
    return stations_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public int getStationsCount() {
    return stations_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Station getStations(int index) {
    return stations_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
      int index) {
    return stations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    for (int i = 0; i < stations_.size(); i++) {
      output.writeMessage(3, stations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    for (int i = 0; i < stations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, stations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.Region)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.Region other = (com.tsuyogoro.sugorokuon.Region) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getStationsList()
        .equals(other.getStationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getStationsCount() > 0) {
      hash = (37 * hash) + STATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getStationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.Region parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.Region parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Region parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.Region prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tsuyogoro.sugorokuon.Region}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.Region)
      com.tsuyogoro.sugorokuon.RegionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.RegionProto.internal_static_tsuyogoro_sugorokuon_Region_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.RegionProto.internal_static_tsuyogoro_sugorokuon_Region_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.Region.class, com.tsuyogoro.sugorokuon.Region.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.Region.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      if (stationsBuilder_ == null) {
        stations_ = java.util.Collections.emptyList();
      } else {
        stations_ = null;
        stationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.RegionProto.internal_static_tsuyogoro_sugorokuon_Region_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Region getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.Region.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Region build() {
      com.tsuyogoro.sugorokuon.Region result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Region buildPartial() {
      com.tsuyogoro.sugorokuon.Region result = new com.tsuyogoro.sugorokuon.Region(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.Region result) {
      if (stationsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          stations_ = java.util.Collections.unmodifiableList(stations_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stations_ = stations_;
      } else {
        result.stations_ = stationsBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.Region result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.Region) {
        return mergeFrom((com.tsuyogoro.sugorokuon.Region)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.Region other) {
      if (other == com.tsuyogoro.sugorokuon.Region.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (stationsBuilder_ == null) {
        if (!other.stations_.isEmpty()) {
          if (stations_.isEmpty()) {
            stations_ = other.stations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStationsIsMutable();
            stations_.addAll(other.stations_);
          }
          onChanged();
        }
      } else {
        if (!other.stations_.isEmpty()) {
          if (stationsBuilder_.isEmpty()) {
            stationsBuilder_.dispose();
            stationsBuilder_ = null;
            stations_ = other.stations_;
            bitField0_ = (bitField0_ & ~0x00000004);
            stationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getStationsFieldBuilder() : null;
          } else {
            stationsBuilder_.addAllMessages(other.stations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.tsuyogoro.sugorokuon.Station m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Station.parser(),
                      extensionRegistry);
              if (stationsBuilder_ == null) {
                ensureStationsIsMutable();
                stations_.add(m);
              } else {
                stationsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.tsuyogoro.sugorokuon.Station> stations_ =
      java.util.Collections.emptyList();
    private void ensureStationsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        stations_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Station>(stations_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> stationsBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Station> getStationsList() {
      if (stationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stations_);
      } else {
        return stationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public int getStationsCount() {
      if (stationsBuilder_ == null) {
        return stations_.size();
      } else {
        return stationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station getStations(int index) {
      if (stationsBuilder_ == null) {
        return stations_.get(index);
      } else {
        return stationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder setStations(
        int index, com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.set(index, value);
        onChanged();
      } else {
        stationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder setStations(
        int index, com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.set(index, builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder addStations(com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.add(value);
        onChanged();
      } else {
        stationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder addStations(
        int index, com.tsuyogoro.sugorokuon.Station value) {
      if (stationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStationsIsMutable();
        stations_.add(index, value);
        onChanged();
      } else {
        stationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder addStations(
        com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.add(builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder addStations(
        int index, com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.add(index, builderForValue.build());
        onChanged();
      } else {
        stationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder addAllStations(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Station> values) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stations_);
        onChanged();
      } else {
        stationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder clearStations() {
      if (stationsBuilder_ == null) {
        stations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        stationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public Builder removeStations(int index) {
      if (stationsBuilder_ == null) {
        ensureStationsIsMutable();
        stations_.remove(index);
        onChanged();
      } else {
        stationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder getStationsBuilder(
        int index) {
      return getStationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.StationOrBuilder getStationsOrBuilder(
        int index) {
      if (stationsBuilder_ == null) {
        return stations_.get(index);  } else {
        return stationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.StationOrBuilder> 
         getStationsOrBuilderList() {
      if (stationsBuilder_ != null) {
        return stationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stations_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder addStationsBuilder() {
      return getStationsFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Station.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder addStationsBuilder(
        int index) {
      return getStationsFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Station.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Station stations = 3 [json_name = "stations"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Station.Builder> 
         getStationsBuilderList() {
      return getStationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> 
        getStationsFieldBuilder() {
      if (stationsBuilder_ == null) {
        stationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder>(
                stations_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        stations_ = null;
      }
      return stationsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.Region)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.Region)
  private static final com.tsuyogoro.sugorokuon.Region DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.Region();
  }

  public static com.tsuyogoro.sugorokuon.Region getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Region>
      PARSER = new com.google.protobuf.AbstractParser<Region>() {
    @java.lang.Override
    public Region parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Region> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Region> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Region getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

