// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Song.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class SongProto {
  private SongProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      SongProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_SongThumbnail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_SongThumbnail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_Song_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_Song_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037tsuyogoro/sugorokuon/Song.proto\022\024tsuyo" +
      "goro.sugorokuon\032\032google/type/datetime.pr" +
      "oto\032!tsuyogoro/sugorokuon/Artist.proto\"S" +
      "\n\rSongThumbnail\022\024\n\005small\030\001 \001(\tR\005small\022\026\n" +
      "\006medium\030\002 \001(\tR\006medium\022\024\n\005large\030\003 \001(\tR\005la" +
      "rge\"\314\001\n\004Song\0224\n\006artist\030\001 \001(\0132\034.tsuyogoro" +
      ".sugorokuon.ArtistR\006artist\022\024\n\005title\030\002 \001(" +
      "\tR\005title\022C\n\nthumbnails\030\003 \001(\0132#.tsuyogoro" +
      ".sugorokuon.SongThumbnailR\nthumbnails\0223\n" +
      "\tonAirTime\030\004 \001(\0132\025.google.type.DateTimeR" +
      "\tonAirTimeB\315\001\n\030com.tsuyogoro.sugorokuonB" +
      "\tSongProtoP\001Z5github.com/bufbuild/buf-to" +
      "ur/gen/tsuyogoro/sugorokuon\242\002\003TSX\252\002\024Tsuy" +
      "ogoro.Sugorokuon\312\002\024Tsuyogoro\\Sugorokuon\342" +
      "\002 Tsuyogoro\\Sugorokuon\\GPBMetadata\352\002\025Tsu" +
      "yogoro::Sugorokuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.DatetimeProto.getDescriptor(),
          com.tsuyogoro.sugorokuon.ArtistProto.getDescriptor(),
        });
    internal_static_tsuyogoro_sugorokuon_SongThumbnail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_SongThumbnail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_SongThumbnail_descriptor,
        new java.lang.String[] { "Small", "Medium", "Large", });
    internal_static_tsuyogoro_sugorokuon_Song_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tsuyogoro_sugorokuon_Song_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_Song_descriptor,
        new java.lang.String[] { "Artist", "Title", "Thumbnails", "OnAirTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.type.DatetimeProto.getDescriptor();
    com.tsuyogoro.sugorokuon.ArtistProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
