// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Song.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface SongThumbnailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.SongThumbnail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string small = 1 [json_name = "small"];</code>
   * @return The small.
   */
  java.lang.String getSmall();
  /**
   * <code>string small = 1 [json_name = "small"];</code>
   * @return The bytes for small.
   */
  com.google.protobuf.ByteString
      getSmallBytes();

  /**
   * <code>string medium = 2 [json_name = "medium"];</code>
   * @return The medium.
   */
  java.lang.String getMedium();
  /**
   * <code>string medium = 2 [json_name = "medium"];</code>
   * @return The bytes for medium.
   */
  com.google.protobuf.ByteString
      getMediumBytes();

  /**
   * <code>string large = 3 [json_name = "large"];</code>
   * @return The large.
   */
  java.lang.String getLarge();
  /**
   * <code>string large = 3 [json_name = "large"];</code>
   * @return The bytes for large.
   */
  com.google.protobuf.ByteString
      getLargeBytes();
}
