// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Song.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * Protobuf type {@code tsuyogoro.sugorokuon.Song}
 */
public final class Song extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.Song)
    SongOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Song.class.getName());
  }
  // Use Song.newBuilder() to construct.
  private Song(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Song() {
    title_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.SongProto.internal_static_tsuyogoro_sugorokuon_Song_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.SongProto.internal_static_tsuyogoro_sugorokuon_Song_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.Song.class, com.tsuyogoro.sugorokuon.Song.Builder.class);
  }

  private int bitField0_;
  public static final int ARTIST_FIELD_NUMBER = 1;
  private com.tsuyogoro.sugorokuon.Artist artist_;
  /**
   * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
   * @return Whether the artist field is set.
   */
  @java.lang.Override
  public boolean hasArtist() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
   * @return The artist.
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Artist getArtist() {
    return artist_ == null ? com.tsuyogoro.sugorokuon.Artist.getDefaultInstance() : artist_;
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.ArtistOrBuilder getArtistOrBuilder() {
    return artist_ == null ? com.tsuyogoro.sugorokuon.Artist.getDefaultInstance() : artist_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THUMBNAILS_FIELD_NUMBER = 3;
  private com.tsuyogoro.sugorokuon.SongThumbnail thumbnails_;
  /**
   * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
   * @return Whether the thumbnails field is set.
   */
  @java.lang.Override
  public boolean hasThumbnails() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
   * @return The thumbnails.
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.SongThumbnail getThumbnails() {
    return thumbnails_ == null ? com.tsuyogoro.sugorokuon.SongThumbnail.getDefaultInstance() : thumbnails_;
  }
  /**
   * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.SongThumbnailOrBuilder getThumbnailsOrBuilder() {
    return thumbnails_ == null ? com.tsuyogoro.sugorokuon.SongThumbnail.getDefaultInstance() : thumbnails_;
  }

  public static final int ONAIRTIME_FIELD_NUMBER = 4;
  private com.google.type.DateTime onAirTime_;
  /**
   * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
   * @return Whether the onAirTime field is set.
   */
  @java.lang.Override
  public boolean hasOnAirTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
   * @return The onAirTime.
   */
  @java.lang.Override
  public com.google.type.DateTime getOnAirTime() {
    return onAirTime_ == null ? com.google.type.DateTime.getDefaultInstance() : onAirTime_;
  }
  /**
   * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
   */
  @java.lang.Override
  public com.google.type.DateTimeOrBuilder getOnAirTimeOrBuilder() {
    return onAirTime_ == null ? com.google.type.DateTime.getDefaultInstance() : onAirTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getArtist());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getThumbnails());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getOnAirTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getArtist());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getThumbnails());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOnAirTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.Song)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.Song other = (com.tsuyogoro.sugorokuon.Song) obj;

    if (hasArtist() != other.hasArtist()) return false;
    if (hasArtist()) {
      if (!getArtist()
          .equals(other.getArtist())) return false;
    }
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasThumbnails() != other.hasThumbnails()) return false;
    if (hasThumbnails()) {
      if (!getThumbnails()
          .equals(other.getThumbnails())) return false;
    }
    if (hasOnAirTime() != other.hasOnAirTime()) return false;
    if (hasOnAirTime()) {
      if (!getOnAirTime()
          .equals(other.getOnAirTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasArtist()) {
      hash = (37 * hash) + ARTIST_FIELD_NUMBER;
      hash = (53 * hash) + getArtist().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasThumbnails()) {
      hash = (37 * hash) + THUMBNAILS_FIELD_NUMBER;
      hash = (53 * hash) + getThumbnails().hashCode();
    }
    if (hasOnAirTime()) {
      hash = (37 * hash) + ONAIRTIME_FIELD_NUMBER;
      hash = (53 * hash) + getOnAirTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.Song parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.Song parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Song parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.Song prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tsuyogoro.sugorokuon.Song}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.Song)
      com.tsuyogoro.sugorokuon.SongOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.SongProto.internal_static_tsuyogoro_sugorokuon_Song_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.SongProto.internal_static_tsuyogoro_sugorokuon_Song_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.Song.class, com.tsuyogoro.sugorokuon.Song.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.Song.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getArtistFieldBuilder();
        getThumbnailsFieldBuilder();
        getOnAirTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      artist_ = null;
      if (artistBuilder_ != null) {
        artistBuilder_.dispose();
        artistBuilder_ = null;
      }
      title_ = "";
      thumbnails_ = null;
      if (thumbnailsBuilder_ != null) {
        thumbnailsBuilder_.dispose();
        thumbnailsBuilder_ = null;
      }
      onAirTime_ = null;
      if (onAirTimeBuilder_ != null) {
        onAirTimeBuilder_.dispose();
        onAirTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.SongProto.internal_static_tsuyogoro_sugorokuon_Song_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Song getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.Song.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Song build() {
      com.tsuyogoro.sugorokuon.Song result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Song buildPartial() {
      com.tsuyogoro.sugorokuon.Song result = new com.tsuyogoro.sugorokuon.Song(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.Song result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.artist_ = artistBuilder_ == null
            ? artist_
            : artistBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.thumbnails_ = thumbnailsBuilder_ == null
            ? thumbnails_
            : thumbnailsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.onAirTime_ = onAirTimeBuilder_ == null
            ? onAirTime_
            : onAirTimeBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.Song) {
        return mergeFrom((com.tsuyogoro.sugorokuon.Song)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.Song other) {
      if (other == com.tsuyogoro.sugorokuon.Song.getDefaultInstance()) return this;
      if (other.hasArtist()) {
        mergeArtist(other.getArtist());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasThumbnails()) {
        mergeThumbnails(other.getThumbnails());
      }
      if (other.hasOnAirTime()) {
        mergeOnAirTime(other.getOnAirTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getArtistFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getThumbnailsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getOnAirTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.tsuyogoro.sugorokuon.Artist artist_;
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Artist, com.tsuyogoro.sugorokuon.Artist.Builder, com.tsuyogoro.sugorokuon.ArtistOrBuilder> artistBuilder_;
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     * @return Whether the artist field is set.
     */
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     * @return The artist.
     */
    public com.tsuyogoro.sugorokuon.Artist getArtist() {
      if (artistBuilder_ == null) {
        return artist_ == null ? com.tsuyogoro.sugorokuon.Artist.getDefaultInstance() : artist_;
      } else {
        return artistBuilder_.getMessage();
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public Builder setArtist(com.tsuyogoro.sugorokuon.Artist value) {
      if (artistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        artist_ = value;
      } else {
        artistBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public Builder setArtist(
        com.tsuyogoro.sugorokuon.Artist.Builder builderForValue) {
      if (artistBuilder_ == null) {
        artist_ = builderForValue.build();
      } else {
        artistBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public Builder mergeArtist(com.tsuyogoro.sugorokuon.Artist value) {
      if (artistBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          artist_ != null &&
          artist_ != com.tsuyogoro.sugorokuon.Artist.getDefaultInstance()) {
          getArtistBuilder().mergeFrom(value);
        } else {
          artist_ = value;
        }
      } else {
        artistBuilder_.mergeFrom(value);
      }
      if (artist_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public Builder clearArtist() {
      bitField0_ = (bitField0_ & ~0x00000001);
      artist_ = null;
      if (artistBuilder_ != null) {
        artistBuilder_.dispose();
        artistBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public com.tsuyogoro.sugorokuon.Artist.Builder getArtistBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getArtistFieldBuilder().getBuilder();
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    public com.tsuyogoro.sugorokuon.ArtistOrBuilder getArtistOrBuilder() {
      if (artistBuilder_ != null) {
        return artistBuilder_.getMessageOrBuilder();
      } else {
        return artist_ == null ?
            com.tsuyogoro.sugorokuon.Artist.getDefaultInstance() : artist_;
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Artist artist = 1 [json_name = "artist"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Artist, com.tsuyogoro.sugorokuon.Artist.Builder, com.tsuyogoro.sugorokuon.ArtistOrBuilder> 
        getArtistFieldBuilder() {
      if (artistBuilder_ == null) {
        artistBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tsuyogoro.sugorokuon.Artist, com.tsuyogoro.sugorokuon.Artist.Builder, com.tsuyogoro.sugorokuon.ArtistOrBuilder>(
                getArtist(),
                getParentForChildren(),
                isClean());
        artist_ = null;
      }
      return artistBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.tsuyogoro.sugorokuon.SongThumbnail thumbnails_;
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.SongThumbnail, com.tsuyogoro.sugorokuon.SongThumbnail.Builder, com.tsuyogoro.sugorokuon.SongThumbnailOrBuilder> thumbnailsBuilder_;
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     * @return Whether the thumbnails field is set.
     */
    public boolean hasThumbnails() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     * @return The thumbnails.
     */
    public com.tsuyogoro.sugorokuon.SongThumbnail getThumbnails() {
      if (thumbnailsBuilder_ == null) {
        return thumbnails_ == null ? com.tsuyogoro.sugorokuon.SongThumbnail.getDefaultInstance() : thumbnails_;
      } else {
        return thumbnailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public Builder setThumbnails(com.tsuyogoro.sugorokuon.SongThumbnail value) {
      if (thumbnailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        thumbnails_ = value;
      } else {
        thumbnailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public Builder setThumbnails(
        com.tsuyogoro.sugorokuon.SongThumbnail.Builder builderForValue) {
      if (thumbnailsBuilder_ == null) {
        thumbnails_ = builderForValue.build();
      } else {
        thumbnailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public Builder mergeThumbnails(com.tsuyogoro.sugorokuon.SongThumbnail value) {
      if (thumbnailsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          thumbnails_ != null &&
          thumbnails_ != com.tsuyogoro.sugorokuon.SongThumbnail.getDefaultInstance()) {
          getThumbnailsBuilder().mergeFrom(value);
        } else {
          thumbnails_ = value;
        }
      } else {
        thumbnailsBuilder_.mergeFrom(value);
      }
      if (thumbnails_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public Builder clearThumbnails() {
      bitField0_ = (bitField0_ & ~0x00000004);
      thumbnails_ = null;
      if (thumbnailsBuilder_ != null) {
        thumbnailsBuilder_.dispose();
        thumbnailsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public com.tsuyogoro.sugorokuon.SongThumbnail.Builder getThumbnailsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getThumbnailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    public com.tsuyogoro.sugorokuon.SongThumbnailOrBuilder getThumbnailsOrBuilder() {
      if (thumbnailsBuilder_ != null) {
        return thumbnailsBuilder_.getMessageOrBuilder();
      } else {
        return thumbnails_ == null ?
            com.tsuyogoro.sugorokuon.SongThumbnail.getDefaultInstance() : thumbnails_;
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.SongThumbnail thumbnails = 3 [json_name = "thumbnails"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.SongThumbnail, com.tsuyogoro.sugorokuon.SongThumbnail.Builder, com.tsuyogoro.sugorokuon.SongThumbnailOrBuilder> 
        getThumbnailsFieldBuilder() {
      if (thumbnailsBuilder_ == null) {
        thumbnailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tsuyogoro.sugorokuon.SongThumbnail, com.tsuyogoro.sugorokuon.SongThumbnail.Builder, com.tsuyogoro.sugorokuon.SongThumbnailOrBuilder>(
                getThumbnails(),
                getParentForChildren(),
                isClean());
        thumbnails_ = null;
      }
      return thumbnailsBuilder_;
    }

    private com.google.type.DateTime onAirTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> onAirTimeBuilder_;
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     * @return Whether the onAirTime field is set.
     */
    public boolean hasOnAirTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     * @return The onAirTime.
     */
    public com.google.type.DateTime getOnAirTime() {
      if (onAirTimeBuilder_ == null) {
        return onAirTime_ == null ? com.google.type.DateTime.getDefaultInstance() : onAirTime_;
      } else {
        return onAirTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public Builder setOnAirTime(com.google.type.DateTime value) {
      if (onAirTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        onAirTime_ = value;
      } else {
        onAirTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public Builder setOnAirTime(
        com.google.type.DateTime.Builder builderForValue) {
      if (onAirTimeBuilder_ == null) {
        onAirTime_ = builderForValue.build();
      } else {
        onAirTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public Builder mergeOnAirTime(com.google.type.DateTime value) {
      if (onAirTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          onAirTime_ != null &&
          onAirTime_ != com.google.type.DateTime.getDefaultInstance()) {
          getOnAirTimeBuilder().mergeFrom(value);
        } else {
          onAirTime_ = value;
        }
      } else {
        onAirTimeBuilder_.mergeFrom(value);
      }
      if (onAirTime_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public Builder clearOnAirTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      onAirTime_ = null;
      if (onAirTimeBuilder_ != null) {
        onAirTimeBuilder_.dispose();
        onAirTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public com.google.type.DateTime.Builder getOnAirTimeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getOnAirTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    public com.google.type.DateTimeOrBuilder getOnAirTimeOrBuilder() {
      if (onAirTimeBuilder_ != null) {
        return onAirTimeBuilder_.getMessageOrBuilder();
      } else {
        return onAirTime_ == null ?
            com.google.type.DateTime.getDefaultInstance() : onAirTime_;
      }
    }
    /**
     * <code>.google.type.DateTime onAirTime = 4 [json_name = "onAirTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> 
        getOnAirTimeFieldBuilder() {
      if (onAirTimeBuilder_ == null) {
        onAirTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder>(
                getOnAirTime(),
                getParentForChildren(),
                isClean());
        onAirTime_ = null;
      }
      return onAirTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.Song)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.Song)
  private static final com.tsuyogoro.sugorokuon.Song DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.Song();
  }

  public static com.tsuyogoro.sugorokuon.Song getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Song>
      PARSER = new com.google.protobuf.AbstractParser<Song>() {
    @java.lang.Override
    public Song parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Song> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Song> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Song getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

