// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/SongService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class SongServiceProto {
  private SongServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      SongServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&tsuyogoro/sugorokuon/SongService.proto" +
      "\022\024tsuyogoro.sugorokuon\032\037tsuyogoro/sugoro" +
      "kuon/Song.proto\"M\n\031GetSongsByStationResp" +
      "onse\0220\n\005songs\030\001 \003(\0132\032.tsuyogoro.sugoroku" +
      "on.SongR\005songsB\324\001\n\030com.tsuyogoro.sugorok" +
      "uonB\020SongServiceProtoP\001Z5github.com/bufb" +
      "uild/buf-tour/gen/tsuyogoro/sugorokuon\242\002" +
      "\003TSX\252\002\024Tsuyogoro.Sugorokuon\312\002\024Tsuyogoro\\" +
      "Sugorokuon\342\002 Tsuyogoro\\Sugorokuon\\GPBMet" +
      "adata\352\002\025Tsuyogoro::Sugorokuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tsuyogoro.sugorokuon.SongProto.getDescriptor(),
        });
    internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_GetSongsByStationResponse_descriptor,
        new java.lang.String[] { "Songs", });
    descriptor.resolveAllFeaturesImmutable();
    com.tsuyogoro.sugorokuon.SongProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
