// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationDetail.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class StationDetailProto {
  private StationDetailProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      StationDetailProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_StationDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_StationDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(tsuyogoro/sugorokuon/StationDetail.pro" +
      "to\022\024tsuyogoro.sugorokuon\032\"tsuyogoro/sugo" +
      "rokuon/Station.proto\"Z\n\rStationDetail\0227\n" +
      "\007station\030\001 \001(\0132\035.tsuyogoro.sugorokuon.St" +
      "ationR\007station\022\020\n\003url\030\002 \001(\tR\003urlB\326\001\n\030com" +
      ".tsuyogoro.sugorokuonB\022StationDetailProt" +
      "oP\001Z5github.com/bufbuild/buf-tour/gen/ts" +
      "uyogoro/sugorokuon\242\002\003TSX\252\002\024Tsuyogoro.Sug" +
      "orokuon\312\002\024Tsuyogoro\\Sugorokuon\342\002 Tsuyogo" +
      "ro\\Sugorokuon\\GPBMetadata\352\002\025Tsuyogoro::S" +
      "ugorokuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tsuyogoro.sugorokuon.StationProto.getDescriptor(),
        });
    internal_static_tsuyogoro_sugorokuon_StationDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_StationDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_StationDetail_descriptor,
        new java.lang.String[] { "Station", "Url", });
    descriptor.resolveAllFeaturesImmutable();
    com.tsuyogoro.sugorokuon.StationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
