// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Station.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class StationProto {
  private StationProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      StationProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_Station_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_Station_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"tsuyogoro/sugorokuon/Station.proto\022\024ts" +
      "uyogoro.sugorokuon\"-\n\007Station\022\016\n\002id\030\001 \001(" +
      "\tR\002id\022\022\n\004name\030\002 \001(\tR\004nameB\320\001\n\030com.tsuyog" +
      "oro.sugorokuonB\014StationProtoP\001Z5github.c" +
      "om/bufbuild/buf-tour/gen/tsuyogoro/sugor" +
      "okuon\242\002\003TSX\252\002\024Tsuyogoro.Sugorokuon\312\002\024Tsu" +
      "yogoro\\Sugorokuon\342\002 Tsuyogoro\\Sugorokuon" +
      "\\GPBMetadata\352\002\025Tsuyogoro::Sugorokuonb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tsuyogoro_sugorokuon_Station_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_Station_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_Station_descriptor,
        new java.lang.String[] { "Id", "Name", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
