// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationService.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public final class StationServiceProto {
  private StationServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      StationServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_GetStationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_GetStationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tsuyogoro_sugorokuon_GetStationsByAreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tsuyogoro_sugorokuon_GetStationsByAreaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)tsuyogoro/sugorokuon/StationService.pr" +
      "oto\022\024tsuyogoro.sugorokuon\032\"tsuyogoro/sug" +
      "orokuon/Station.proto\032!tsuyogoro/sugorok" +
      "uon/Region.proto\"O\n\022GetStationResponse\0229" +
      "\n\010stations\030\001 \003(\0132\035.tsuyogoro.sugorokuon." +
      "StationR\010stations\"\216\001\n\033GetStationsByRegio" +
      "nResponse\0224\n\006region\030\001 \001(\0132\034.tsuyogoro.su" +
      "gorokuon.RegionR\006region\0229\n\010stations\030\002 \003(" +
      "\0132\035.tsuyogoro.sugorokuon.StationR\010statio" +
      "ns\"V\n\031GetStationsByAreaResponse\0229\n\010stati" +
      "ons\030\001 \003(\0132\035.tsuyogoro.sugorokuon.Station" +
      "R\010stationsB\327\001\n\030com.tsuyogoro.sugorokuonB" +
      "\023StationServiceProtoP\001Z5github.com/bufbu" +
      "ild/buf-tour/gen/tsuyogoro/sugorokuon\242\002\003" +
      "TSX\252\002\024Tsuyogoro.Sugorokuon\312\002\024Tsuyogoro\\S" +
      "ugorokuon\342\002 Tsuyogoro\\Sugorokuon\\GPBMeta" +
      "data\352\002\025Tsuyogoro::Sugorokuonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tsuyogoro.sugorokuon.StationProto.getDescriptor(),
          com.tsuyogoro.sugorokuon.RegionProto.getDescriptor(),
        });
    internal_static_tsuyogoro_sugorokuon_GetStationResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tsuyogoro_sugorokuon_GetStationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_GetStationResponse_descriptor,
        new java.lang.String[] { "Stations", });
    internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_GetStationsByRegionResponse_descriptor,
        new java.lang.String[] { "Region", "Stations", });
    internal_static_tsuyogoro_sugorokuon_GetStationsByAreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tsuyogoro_sugorokuon_GetStationsByAreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tsuyogoro_sugorokuon_GetStationsByAreaResponse_descriptor,
        new java.lang.String[] { "Stations", });
    descriptor.resolveAllFeaturesImmutable();
    com.tsuyogoro.sugorokuon.StationProto.getDescriptor();
    com.tsuyogoro.sugorokuon.RegionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
