// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/StationDetail.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.tsuyogoro.sugorokuon;

@kotlin.jvm.JvmName("-initializestationDetail")
public inline fun stationDetail(block: com.tsuyogoro.sugorokuon.StationDetailKt.Dsl.() -> kotlin.Unit): com.tsuyogoro.sugorokuon.StationDetail =
  com.tsuyogoro.sugorokuon.StationDetailKt.Dsl._create(com.tsuyogoro.sugorokuon.StationDetail.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `tsuyogoro.sugorokuon.StationDetail`
 */
public object StationDetailKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.tsuyogoro.sugorokuon.StationDetail.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.tsuyogoro.sugorokuon.StationDetail.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.tsuyogoro.sugorokuon.StationDetail = _builder.build()

    /**
     * `.tsuyogoro.sugorokuon.Station station = 1 [json_name = "station"];`
     */
    public var station: com.tsuyogoro.sugorokuon.Station
      @JvmName("getStation")
      get() = _builder.station
      @JvmName("setStation")
      set(value) {
        _builder.station = value
      }
    /**
     * `.tsuyogoro.sugorokuon.Station station = 1 [json_name = "station"];`
     */
    public fun clearStation() {
      _builder.clearStation()
    }
    /**
     * `.tsuyogoro.sugorokuon.Station station = 1 [json_name = "station"];`
     * @return Whether the station field is set.
     */
    public fun hasStation(): kotlin.Boolean {
      return _builder.hasStation()
    }

    public val StationDetailKt.Dsl.stationOrNull: com.tsuyogoro.sugorokuon.Station?
      get() = _builder.stationOrNull

    /**
     * `string url = 2 [json_name = "url"];`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.url
      @JvmName("setUrl")
      set(value) {
        _builder.url = value
      }
    /**
     * `string url = 2 [json_name = "url"];`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.tsuyogoro.sugorokuon.StationDetail.copy(block: `com.tsuyogoro.sugorokuon`.StationDetailKt.Dsl.() -> kotlin.Unit): com.tsuyogoro.sugorokuon.StationDetail =
  `com.tsuyogoro.sugorokuon`.StationDetailKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.tsuyogoro.sugorokuon.StationDetailOrBuilder.stationOrNull: com.tsuyogoro.sugorokuon.Station?
  get() = if (hasStation()) getStation() else null

