// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Timetable.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

/**
 * Protobuf type {@code tsuyogoro.sugorokuon.Timetable}
 */
public final class Timetable extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tsuyogoro.sugorokuon.Timetable)
    TimetableOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Timetable.class.getName());
  }
  // Use Timetable.newBuilder() to construct.
  private Timetable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Timetable() {
    programs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tsuyogoro.sugorokuon.TimetableProto.internal_static_tsuyogoro_sugorokuon_Timetable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tsuyogoro.sugorokuon.TimetableProto.internal_static_tsuyogoro_sugorokuon_Timetable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tsuyogoro.sugorokuon.Timetable.class, com.tsuyogoro.sugorokuon.Timetable.Builder.class);
  }

  private int bitField0_;
  public static final int DATE_FIELD_NUMBER = 1;
  private com.google.type.DateTime date_;
  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   * @return The date.
   */
  @java.lang.Override
  public com.google.type.DateTime getDate() {
    return date_ == null ? com.google.type.DateTime.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   */
  @java.lang.Override
  public com.google.type.DateTimeOrBuilder getDateOrBuilder() {
    return date_ == null ? com.google.type.DateTime.getDefaultInstance() : date_;
  }

  public static final int STATION_FIELD_NUMBER = 2;
  private com.tsuyogoro.sugorokuon.Station station_;
  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  @java.lang.Override
  public boolean hasStation() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   * @return The station.
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Station getStation() {
    return station_ == null ? com.tsuyogoro.sugorokuon.Station.getDefaultInstance() : station_;
  }
  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.StationOrBuilder getStationOrBuilder() {
    return station_ == null ? com.tsuyogoro.sugorokuon.Station.getDefaultInstance() : station_;
  }

  public static final int PROGRAMS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.tsuyogoro.sugorokuon.Program> programs_;
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tsuyogoro.sugorokuon.Program> getProgramsList() {
    return programs_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tsuyogoro.sugorokuon.ProgramOrBuilder> 
      getProgramsOrBuilderList() {
    return programs_;
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  @java.lang.Override
  public int getProgramsCount() {
    return programs_.size();
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Program getPrograms(int index) {
    return programs_.get(index);
  }
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  @java.lang.Override
  public com.tsuyogoro.sugorokuon.ProgramOrBuilder getProgramsOrBuilder(
      int index) {
    return programs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getStation());
    }
    for (int i = 0; i < programs_.size(); i++) {
      output.writeMessage(3, programs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStation());
    }
    for (int i = 0; i < programs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, programs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tsuyogoro.sugorokuon.Timetable)) {
      return super.equals(obj);
    }
    com.tsuyogoro.sugorokuon.Timetable other = (com.tsuyogoro.sugorokuon.Timetable) obj;

    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (hasStation() != other.hasStation()) return false;
    if (hasStation()) {
      if (!getStation()
          .equals(other.getStation())) return false;
    }
    if (!getProgramsList()
        .equals(other.getProgramsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasStation()) {
      hash = (37 * hash) + STATION_FIELD_NUMBER;
      hash = (53 * hash) + getStation().hashCode();
    }
    if (getProgramsCount() > 0) {
      hash = (37 * hash) + PROGRAMS_FIELD_NUMBER;
      hash = (53 * hash) + getProgramsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tsuyogoro.sugorokuon.Timetable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tsuyogoro.sugorokuon.Timetable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tsuyogoro.sugorokuon.Timetable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tsuyogoro.sugorokuon.Timetable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tsuyogoro.sugorokuon.Timetable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tsuyogoro.sugorokuon.Timetable)
      com.tsuyogoro.sugorokuon.TimetableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tsuyogoro.sugorokuon.TimetableProto.internal_static_tsuyogoro_sugorokuon_Timetable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tsuyogoro.sugorokuon.TimetableProto.internal_static_tsuyogoro_sugorokuon_Timetable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tsuyogoro.sugorokuon.Timetable.class, com.tsuyogoro.sugorokuon.Timetable.Builder.class);
    }

    // Construct using com.tsuyogoro.sugorokuon.Timetable.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDateFieldBuilder();
        getStationFieldBuilder();
        getProgramsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      date_ = null;
      if (dateBuilder_ != null) {
        dateBuilder_.dispose();
        dateBuilder_ = null;
      }
      station_ = null;
      if (stationBuilder_ != null) {
        stationBuilder_.dispose();
        stationBuilder_ = null;
      }
      if (programsBuilder_ == null) {
        programs_ = java.util.Collections.emptyList();
      } else {
        programs_ = null;
        programsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tsuyogoro.sugorokuon.TimetableProto.internal_static_tsuyogoro_sugorokuon_Timetable_descriptor;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Timetable getDefaultInstanceForType() {
      return com.tsuyogoro.sugorokuon.Timetable.getDefaultInstance();
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Timetable build() {
      com.tsuyogoro.sugorokuon.Timetable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tsuyogoro.sugorokuon.Timetable buildPartial() {
      com.tsuyogoro.sugorokuon.Timetable result = new com.tsuyogoro.sugorokuon.Timetable(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tsuyogoro.sugorokuon.Timetable result) {
      if (programsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          programs_ = java.util.Collections.unmodifiableList(programs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.programs_ = programs_;
      } else {
        result.programs_ = programsBuilder_.build();
      }
    }

    private void buildPartial0(com.tsuyogoro.sugorokuon.Timetable result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.date_ = dateBuilder_ == null
            ? date_
            : dateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.station_ = stationBuilder_ == null
            ? station_
            : stationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tsuyogoro.sugorokuon.Timetable) {
        return mergeFrom((com.tsuyogoro.sugorokuon.Timetable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tsuyogoro.sugorokuon.Timetable other) {
      if (other == com.tsuyogoro.sugorokuon.Timetable.getDefaultInstance()) return this;
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.hasStation()) {
        mergeStation(other.getStation());
      }
      if (programsBuilder_ == null) {
        if (!other.programs_.isEmpty()) {
          if (programs_.isEmpty()) {
            programs_ = other.programs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureProgramsIsMutable();
            programs_.addAll(other.programs_);
          }
          onChanged();
        }
      } else {
        if (!other.programs_.isEmpty()) {
          if (programsBuilder_.isEmpty()) {
            programsBuilder_.dispose();
            programsBuilder_ = null;
            programs_ = other.programs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            programsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getProgramsFieldBuilder() : null;
          } else {
            programsBuilder_.addAllMessages(other.programs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.tsuyogoro.sugorokuon.Program m =
                  input.readMessage(
                      com.tsuyogoro.sugorokuon.Program.parser(),
                      extensionRegistry);
              if (programsBuilder_ == null) {
                ensureProgramsIsMutable();
                programs_.add(m);
              } else {
                programsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.type.DateTime date_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> dateBuilder_;
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     * @return The date.
     */
    public com.google.type.DateTime getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.type.DateTime.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public Builder setDate(com.google.type.DateTime value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
      } else {
        dateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public Builder setDate(
        com.google.type.DateTime.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public Builder mergeDate(com.google.type.DateTime value) {
      if (dateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          date_ != null &&
          date_ != com.google.type.DateTime.getDefaultInstance()) {
          getDateBuilder().mergeFrom(value);
        } else {
          date_ = value;
        }
      } else {
        dateBuilder_.mergeFrom(value);
      }
      if (date_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public Builder clearDate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      date_ = null;
      if (dateBuilder_ != null) {
        dateBuilder_.dispose();
        dateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public com.google.type.DateTime.Builder getDateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    public com.google.type.DateTimeOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.type.DateTime.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private com.tsuyogoro.sugorokuon.Station station_;
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> stationBuilder_;
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     * @return Whether the station field is set.
     */
    public boolean hasStation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     * @return The station.
     */
    public com.tsuyogoro.sugorokuon.Station getStation() {
      if (stationBuilder_ == null) {
        return station_ == null ? com.tsuyogoro.sugorokuon.Station.getDefaultInstance() : station_;
      } else {
        return stationBuilder_.getMessage();
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public Builder setStation(com.tsuyogoro.sugorokuon.Station value) {
      if (stationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        station_ = value;
      } else {
        stationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public Builder setStation(
        com.tsuyogoro.sugorokuon.Station.Builder builderForValue) {
      if (stationBuilder_ == null) {
        station_ = builderForValue.build();
      } else {
        stationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public Builder mergeStation(com.tsuyogoro.sugorokuon.Station value) {
      if (stationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          station_ != null &&
          station_ != com.tsuyogoro.sugorokuon.Station.getDefaultInstance()) {
          getStationBuilder().mergeFrom(value);
        } else {
          station_ = value;
        }
      } else {
        stationBuilder_.mergeFrom(value);
      }
      if (station_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public Builder clearStation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      station_ = null;
      if (stationBuilder_ != null) {
        stationBuilder_.dispose();
        stationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public com.tsuyogoro.sugorokuon.Station.Builder getStationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStationFieldBuilder().getBuilder();
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    public com.tsuyogoro.sugorokuon.StationOrBuilder getStationOrBuilder() {
      if (stationBuilder_ != null) {
        return stationBuilder_.getMessageOrBuilder();
      } else {
        return station_ == null ?
            com.tsuyogoro.sugorokuon.Station.getDefaultInstance() : station_;
      }
    }
    /**
     * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder> 
        getStationFieldBuilder() {
      if (stationBuilder_ == null) {
        stationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tsuyogoro.sugorokuon.Station, com.tsuyogoro.sugorokuon.Station.Builder, com.tsuyogoro.sugorokuon.StationOrBuilder>(
                getStation(),
                getParentForChildren(),
                isClean());
        station_ = null;
      }
      return stationBuilder_;
    }

    private java.util.List<com.tsuyogoro.sugorokuon.Program> programs_ =
      java.util.Collections.emptyList();
    private void ensureProgramsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        programs_ = new java.util.ArrayList<com.tsuyogoro.sugorokuon.Program>(programs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Program, com.tsuyogoro.sugorokuon.Program.Builder, com.tsuyogoro.sugorokuon.ProgramOrBuilder> programsBuilder_;

    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Program> getProgramsList() {
      if (programsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(programs_);
      } else {
        return programsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public int getProgramsCount() {
      if (programsBuilder_ == null) {
        return programs_.size();
      } else {
        return programsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Program getPrograms(int index) {
      if (programsBuilder_ == null) {
        return programs_.get(index);
      } else {
        return programsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder setPrograms(
        int index, com.tsuyogoro.sugorokuon.Program value) {
      if (programsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProgramsIsMutable();
        programs_.set(index, value);
        onChanged();
      } else {
        programsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder setPrograms(
        int index, com.tsuyogoro.sugorokuon.Program.Builder builderForValue) {
      if (programsBuilder_ == null) {
        ensureProgramsIsMutable();
        programs_.set(index, builderForValue.build());
        onChanged();
      } else {
        programsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder addPrograms(com.tsuyogoro.sugorokuon.Program value) {
      if (programsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProgramsIsMutable();
        programs_.add(value);
        onChanged();
      } else {
        programsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder addPrograms(
        int index, com.tsuyogoro.sugorokuon.Program value) {
      if (programsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProgramsIsMutable();
        programs_.add(index, value);
        onChanged();
      } else {
        programsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder addPrograms(
        com.tsuyogoro.sugorokuon.Program.Builder builderForValue) {
      if (programsBuilder_ == null) {
        ensureProgramsIsMutable();
        programs_.add(builderForValue.build());
        onChanged();
      } else {
        programsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder addPrograms(
        int index, com.tsuyogoro.sugorokuon.Program.Builder builderForValue) {
      if (programsBuilder_ == null) {
        ensureProgramsIsMutable();
        programs_.add(index, builderForValue.build());
        onChanged();
      } else {
        programsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder addAllPrograms(
        java.lang.Iterable<? extends com.tsuyogoro.sugorokuon.Program> values) {
      if (programsBuilder_ == null) {
        ensureProgramsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, programs_);
        onChanged();
      } else {
        programsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder clearPrograms() {
      if (programsBuilder_ == null) {
        programs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        programsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public Builder removePrograms(int index) {
      if (programsBuilder_ == null) {
        ensureProgramsIsMutable();
        programs_.remove(index);
        onChanged();
      } else {
        programsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Program.Builder getProgramsBuilder(
        int index) {
      return getProgramsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public com.tsuyogoro.sugorokuon.ProgramOrBuilder getProgramsOrBuilder(
        int index) {
      if (programsBuilder_ == null) {
        return programs_.get(index);  } else {
        return programsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public java.util.List<? extends com.tsuyogoro.sugorokuon.ProgramOrBuilder> 
         getProgramsOrBuilderList() {
      if (programsBuilder_ != null) {
        return programsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(programs_);
      }
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Program.Builder addProgramsBuilder() {
      return getProgramsFieldBuilder().addBuilder(
          com.tsuyogoro.sugorokuon.Program.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public com.tsuyogoro.sugorokuon.Program.Builder addProgramsBuilder(
        int index) {
      return getProgramsFieldBuilder().addBuilder(
          index, com.tsuyogoro.sugorokuon.Program.getDefaultInstance());
    }
    /**
     * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
     */
    public java.util.List<com.tsuyogoro.sugorokuon.Program.Builder> 
         getProgramsBuilderList() {
      return getProgramsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.tsuyogoro.sugorokuon.Program, com.tsuyogoro.sugorokuon.Program.Builder, com.tsuyogoro.sugorokuon.ProgramOrBuilder> 
        getProgramsFieldBuilder() {
      if (programsBuilder_ == null) {
        programsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.tsuyogoro.sugorokuon.Program, com.tsuyogoro.sugorokuon.Program.Builder, com.tsuyogoro.sugorokuon.ProgramOrBuilder>(
                programs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        programs_ = null;
      }
      return programsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tsuyogoro.sugorokuon.Timetable)
  }

  // @@protoc_insertion_point(class_scope:tsuyogoro.sugorokuon.Timetable)
  private static final com.tsuyogoro.sugorokuon.Timetable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tsuyogoro.sugorokuon.Timetable();
  }

  public static com.tsuyogoro.sugorokuon.Timetable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Timetable>
      PARSER = new com.google.protobuf.AbstractParser<Timetable>() {
    @java.lang.Override
    public Timetable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Timetable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Timetable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tsuyogoro.sugorokuon.Timetable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

