// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tsuyogoro/sugorokuon/Timetable.proto
// Protobuf Java Version: 4.29.1

package com.tsuyogoro.sugorokuon;

public interface TimetableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tsuyogoro.sugorokuon.Timetable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   * @return The date.
   */
  com.google.type.DateTime getDate();
  /**
   * <code>.google.type.DateTime date = 1 [json_name = "date"];</code>
   */
  com.google.type.DateTimeOrBuilder getDateOrBuilder();

  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   * @return Whether the station field is set.
   */
  boolean hasStation();
  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   * @return The station.
   */
  com.tsuyogoro.sugorokuon.Station getStation();
  /**
   * <code>.tsuyogoro.sugorokuon.Station station = 2 [json_name = "station"];</code>
   */
  com.tsuyogoro.sugorokuon.StationOrBuilder getStationOrBuilder();

  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  java.util.List<com.tsuyogoro.sugorokuon.Program> 
      getProgramsList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  com.tsuyogoro.sugorokuon.Program getPrograms(int index);
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  int getProgramsCount();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  java.util.List<? extends com.tsuyogoro.sugorokuon.ProgramOrBuilder> 
      getProgramsOrBuilderList();
  /**
   * <code>repeated .tsuyogoro.sugorokuon.Program programs = 3 [json_name = "programs"];</code>
   */
  com.tsuyogoro.sugorokuon.ProgramOrBuilder getProgramsOrBuilder(
      int index);
}
