// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pet/v1/pet.proto
// Protobuf Java Version: 4.29.1

package com.pet.v1;

public interface DeletePetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pet.v1.DeletePetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pet_id = 1 [json_name = "petId"];</code>
   * @return The petId.
   */
  java.lang.String getPetId();
  /**
   * <code>string pet_id = 1 [json_name = "petId"];</code>
   * @return The bytes for petId.
   */
  com.google.protobuf.ByteString
      getPetIdBytes();
}
