// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pet/v1/pet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.pet.v1;

@kotlin.jvm.JvmName("-initializepet")
public inline fun pet(block: com.pet.v1.PetKt.Dsl.() -> kotlin.Unit): com.pet.v1.Pet =
  com.pet.v1.PetKt.Dsl._create(com.pet.v1.Pet.newBuilder()).apply { block() }._build()
/**
 * ```
 * Pet represents a pet in the pet store.
 * ```
 *
 * Protobuf type `pet.v1.Pet`
 */
public object PetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.pet.v1.Pet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.pet.v1.Pet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.pet.v1.Pet = _builder.build()

    /**
     * `.pet.v1.PetType pet_type = 1 [json_name = "petType"];`
     */
    public var petType: com.pet.v1.PetType
      @JvmName("getPetType")
      get() = _builder.petType
      @JvmName("setPetType")
      set(value) {
        _builder.petType = value
      }
    public var petTypeValue: kotlin.Int
      @JvmName("getPetTypeValue")
      get() = _builder.petTypeValue
      @JvmName("setPetTypeValue")
      set(value) {
        _builder.petTypeValue = value
      }
    /**
     * `.pet.v1.PetType pet_type = 1 [json_name = "petType"];`
     */
    public fun clearPetType() {
      _builder.clearPetType()
    }

    /**
     * `string pet_id = 2 [json_name = "petId"];`
     */
    public var petId: kotlin.String
      @JvmName("getPetId")
      get() = _builder.petId
      @JvmName("setPetId")
      set(value) {
        _builder.petId = value
      }
    /**
     * `string pet_id = 2 [json_name = "petId"];`
     */
    public fun clearPetId() {
      _builder.clearPetId()
    }

    /**
     * `string name = 3 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 3 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.google.type.DateTime created_at = 4 [json_name = "createdAt"];`
     */
    public var createdAt: com.google.type.DateTime
      @JvmName("getCreatedAt")
      get() = _builder.createdAt
      @JvmName("setCreatedAt")
      set(value) {
        _builder.createdAt = value
      }
    /**
     * `.google.type.DateTime created_at = 4 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.google.type.DateTime created_at = 4 [json_name = "createdAt"];`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val PetKt.Dsl.createdAtOrNull: com.google.type.DateTime?
      get() = _builder.createdAtOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.pet.v1.Pet.copy(block: `com.pet.v1`.PetKt.Dsl.() -> kotlin.Unit): com.pet.v1.Pet =
  `com.pet.v1`.PetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.pet.v1.PetOrBuilder.createdAtOrNull: com.google.type.DateTime?
  get() = if (hasCreatedAt()) getCreatedAt() else null

