// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pet/v1/pet.proto
// Protobuf Java Version: 4.29.1

package com.pet.v1;

/**
 * <pre>
 * PetType represents the different types of pets in the pet store.
 * </pre>
 *
 * Protobuf enum {@code pet.v1.PetType}
 */
public enum PetType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PET_TYPE_UNSPECIFIED = 0;</code>
   */
  PET_TYPE_UNSPECIFIED(0),
  /**
   * <code>PET_TYPE_CAT = 1;</code>
   */
  PET_TYPE_CAT(1),
  /**
   * <code>PET_TYPE_DOG = 2;</code>
   */
  PET_TYPE_DOG(2),
  /**
   * <code>PET_TYPE_SNAKE = 3;</code>
   */
  PET_TYPE_SNAKE(3),
  /**
   * <code>PET_TYPE_HAMSTER = 4;</code>
   */
  PET_TYPE_HAMSTER(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      PetType.class.getName());
  }
  /**
   * <code>PET_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int PET_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PET_TYPE_CAT = 1;</code>
   */
  public static final int PET_TYPE_CAT_VALUE = 1;
  /**
   * <code>PET_TYPE_DOG = 2;</code>
   */
  public static final int PET_TYPE_DOG_VALUE = 2;
  /**
   * <code>PET_TYPE_SNAKE = 3;</code>
   */
  public static final int PET_TYPE_SNAKE_VALUE = 3;
  /**
   * <code>PET_TYPE_HAMSTER = 4;</code>
   */
  public static final int PET_TYPE_HAMSTER_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PetType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PetType forNumber(int value) {
    switch (value) {
      case 0: return PET_TYPE_UNSPECIFIED;
      case 1: return PET_TYPE_CAT;
      case 2: return PET_TYPE_DOG;
      case 3: return PET_TYPE_SNAKE;
      case 4: return PET_TYPE_HAMSTER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PetType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PetType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PetType>() {
          public PetType findValueByNumber(int number) {
            return PetType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pet.v1.PetProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final PetType[] VALUES = values();

  public static PetType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PetType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pet.v1.PetType)
}

