// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pet/v1/pet.proto
// Protobuf Java Version: 4.29.1

package com.pet.v1;

public interface PutPetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pet.v1.PutPetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pet.v1.PetType pet_type = 1 [json_name = "petType"];</code>
   * @return The enum numeric value on the wire for petType.
   */
  int getPetTypeValue();
  /**
   * <code>.pet.v1.PetType pet_type = 1 [json_name = "petType"];</code>
   * @return The petType.
   */
  com.pet.v1.PetType getPetType();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
